using System.IO;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;
using UnityEngine.SceneManagement;

namespace VFXComposer.Gallery.Editor
{
    /// <summary>
    /// Deterministic builder for the two gallery scenes (GALLERY_SPEC.md
    /// sections 1-2). Scenes are generated by this script rather than
    /// hand-authored .unity YAML (registered route decision: hand-written scene
    /// YAML is fragile across Unity versions; the builder is re-runnable and
    /// reviewable). Menu + batchmode entry point.
    /// </summary>
    public static class GallerySceneBuilder
    {
        private const string GalleryRootPath = "Assets/VFX/Gallery/";

        [MenuItem("VFXComposer/Gallery/Rebuild Gallery Scenes")]
        public static void RebuildAll()
        {
            BuildVolumeProfile();
            BuildPageSet("3d");
            BuildPageSet("2d");
            BuildScene(false);
            BuildScene(true);
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            Debug.Log("[GallerySceneBuilder] Gallery scenes rebuilt.");
        }

        /// <summary>Batchmode entry (tools/Invoke-Unity.ps1 -executeMethod).</summary>
        public static void RebuildFromBatchmode()
        {
            RebuildAll();
            EditorApplication.Exit(0);
        }

        private static void BuildVolumeProfile()
        {
            string path = GalleryRootPath + "GalleryVolume.asset";
            var profile = AssetDatabase.LoadAssetAtPath<VolumeProfile>(path);
            if (profile == null)
            {
                profile = ScriptableObject.CreateInstance<VolumeProfile>();
                AssetDatabase.CreateAsset(profile, path);
            }
            if (!profile.TryGet(out Bloom bloom))
            {
                bloom = profile.Add<Bloom>();
                // Volume components are sub-objects; without this they vanish on reload.
                AssetDatabase.AddObjectToAsset(bloom, profile);
            }
            bloom.active = true;
            bloom.threshold.Override(1.0f);
            bloom.intensity.Override(0.6f);
            bloom.scatter.Override(0.7f);
            bloom.highQualityFiltering.Override(true);
            if (!profile.TryGet(out Tonemapping tone))
            {
                tone = profile.Add<Tonemapping>();
                AssetDatabase.AddObjectToAsset(tone, profile);
            }
            tone.active = true;
            tone.mode.Override(TonemappingMode.Neutral);
            EditorUtility.SetDirty(profile);
            AssetDatabase.SaveAssetIfDirty(profile);
        }

        private static void BuildPageSet(string dimension)
        {
            string path = GalleryRootPath + (dimension == "2d" ? "GalleryPages_2D.asset" : "GalleryPages_3D.asset");
            var pageSet = AssetDatabase.LoadAssetAtPath<GalleryPageSet>(path);
            if (pageSet == null)
            {
                pageSet = ScriptableObject.CreateInstance<GalleryPageSet>();
                AssetDatabase.CreateAsset(pageSet, path);
            }
            var so = new SerializedObject(pageSet);
            so.FindProperty("dimension").stringValue = dimension;
            so.FindProperty("prefabRootPath").stringValue = "Assets/VFX/Generated/";
            SerializedProperty pages = so.FindProperty("pages");
            pages.arraySize = 2;

            // Page 1: structure page — element:none neutral products, one row of
            // archetypes to be filled as archetype coverage grows (holes are normal).
            SerializedProperty p0 = pages.GetArrayElementAtIndex(0);
            p0.FindPropertyRelative("title").stringValue = "结构页（element:none 中性）";
            p0.FindPropertyRelative("mode").enumValueIndex = (int)GalleryPageMode.Matrix3x3;
            p0.FindPropertyRelative("rowAxis").enumValueIndex = (int)GalleryAxis.Archetype;
            p0.FindPropertyRelative("colAxis").enumValueIndex = (int)GalleryAxis.Element;
            SetStringArray(p0.FindPropertyRelative("rowValues"), "", "", "");
            SetStringArray(p0.FindPropertyRelative("colValues"), "none", "none", "none");
            p0.FindPropertyRelative("fixedElement").stringValue = "none";
            p0.FindPropertyRelative("fixedStyle").stringValue = "none";
            p0.FindPropertyRelative("fixedTier").stringValue = "PM";

            // Page 2: paradigm verdict page (ADR-010 section 8 user-judgement face).
            SerializedProperty p1 = pages.GetArrayElementAtIndex(1);
            p1.FindPropertyRelative("title").stringValue = "范式判定页（原型×元素，cartoon）";
            p1.FindPropertyRelative("mode").enumValueIndex = (int)GalleryPageMode.Matrix3x3;
            p1.FindPropertyRelative("rowAxis").enumValueIndex = (int)GalleryAxis.Archetype;
            p1.FindPropertyRelative("colAxis").enumValueIndex = (int)GalleryAxis.Element;
            SetStringArray(p1.FindPropertyRelative("rowValues"), "", "", "");
            SetStringArray(p1.FindPropertyRelative("colValues"), "fire", "ice", "lightning");
            p1.FindPropertyRelative("fixedStyle").stringValue = "cartoon";
            p1.FindPropertyRelative("fixedTier").stringValue = "PM";

            so.ApplyModifiedPropertiesWithoutUndo();
            EditorUtility.SetDirty(pageSet);
        }

        private static void SetStringArray(SerializedProperty arrayProp, string a, string b, string c)
        {
            arrayProp.arraySize = 3;
            arrayProp.GetArrayElementAtIndex(0).stringValue = a;
            arrayProp.GetArrayElementAtIndex(1).stringValue = b;
            arrayProp.GetArrayElementAtIndex(2).stringValue = c;
        }

        private static void BuildScene(bool is2D)
        {
            string scenePath = GalleryRootPath + (is2D ? "VFXGallery_2D.unity" : "VFXGallery_3D.unity");
            Scene scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);

            var root = new GameObject("GalleryRoot");

            // Camera
            var cameraGo = new GameObject("Main Camera");
            cameraGo.tag = "MainCamera";
            cameraGo.transform.SetParent(root.transform);
            var camera = cameraGo.AddComponent<Camera>();
            camera.backgroundColor = new Color(0.035f, 0.04f, 0.055f, 1f);
            camera.clearFlags = CameraClearFlags.SolidColor;
            camera.allowHDR = true;
            camera.allowMSAA = false;
            if (is2D)
            {
                camera.orthographic = true;
                camera.orthographicSize = 6f;
                camera.transform.position = new Vector3(0f, 0f, -10f);
            }
            else
            {
                camera.fieldOfView = 45f;
                camera.transform.position = new Vector3(0f, 4.5f, -11f);
                camera.transform.rotation = Quaternion.Euler(15f, 0f, 0f);
            }
            cameraGo.AddComponent<UniversalAdditionalCameraData>();

            // Post volume (Bloom + Tonemapping, toggleable at runtime)
            var volumeGo = new GameObject("Global Volume");
            volumeGo.transform.SetParent(root.transform);
            var volume = volumeGo.AddComponent<Volume>();
            volume.isGlobal = true;
            volume.priority = 0f;
            volume.sharedProfile = AssetDatabase.LoadAssetAtPath<VolumeProfile>(GalleryRootPath + "GalleryVolume.asset");

            // Ground
            GameObject ground;
            if (is2D)
            {
                ground = new GameObject("Ground");
                ground.transform.SetParent(root.transform);
                ground.transform.position = new Vector3(0f, -5.5f, 0f);
            }
            else
            {
                ground = GameObject.CreatePrimitive(PrimitiveType.Plane);
                ground.name = "Ground";
                ground.transform.SetParent(root.transform);
                ground.transform.localScale = new Vector3(2f, 1f, 2f);
                Object.DestroyImmediate(ground.GetComponent<Collider>());
            }

            // Grid lines container (visual reference only; toggled off for capture)
            var gridLines = new GameObject("GridLines");
            gridLines.transform.SetParent(root.transform);

            // Cells 3x3
            var cells = new GameObject("Cells");
            cells.transform.SetParent(root.transform);
            var anchors = new Transform[9];
            float dx = is2D ? 4.0f : 3.5f;
            float dy = is2D ? 3.2f : 3.0f;
            for (int r = 0; r < 3; r++)
            {
                for (int c = 0; c < 3; c++)
                {
                    var cell = new GameObject($"Cell_{r}_{c}");
                    cell.transform.SetParent(cells.transform);
                    float x = (c - 1) * dx;
                    float y = (1 - r) * dy;
                    cell.transform.position = is2D
                        ? new Vector3(x, y, 0f)
                        : new Vector3(x, 0.5f, (1 - r) * dy);
                    if (is2D) cell.transform.position = new Vector3(x, y, 0f);

                    var anchor = new GameObject("Anchor");
                    anchor.transform.SetParent(cell.transform);
                    anchor.transform.localPosition = Vector3.zero;

                    // Neutral proxy for target-acting archetypes (part of the
                    // gallery, never referenced by product assets: GA-4).
                    GameObject proxy = is2D ? new GameObject("TargetProxy") : GameObject.CreatePrimitive(PrimitiveType.Capsule);
                    proxy.name = "TargetProxy";
                    proxy.transform.SetParent(cell.transform);
                    proxy.transform.localPosition = new Vector3(0f, is2D ? 0f : 0.9f, is2D ? 0f : 0.8f);
                    proxy.transform.localScale = Vector3.one * 0.55f;
                    if (!is2D)
                    {
                        var proxyCollider = proxy.GetComponent<Collider>();
                        if (proxyCollider != null) Object.DestroyImmediate(proxyCollider);
                        proxy.SetActive(false); // enabled per-page when a target-acting archetype loads
                    }

                    anchors[r * 3 + c] = anchor.transform;
                }
            }

            // Inspection light: exists but disabled by default (GA-2).
            var lightGo = new GameObject("InspectionLight");
            lightGo.transform.SetParent(root.transform);
            var inspectionLight = lightGo.AddComponent<Light>();
            inspectionLight.type = LightType.Directional;
            inspectionLight.intensity = 0.6f;
            inspectionLight.enabled = false;
            lightGo.transform.rotation = Quaternion.Euler(45f, -30f, 0f);

            if (is2D)
            {
                // Global Light2D so 2D-lit layers are visible at all.
                var globalLight = new GameObject("GlobalLight2D");
                globalLight.transform.SetParent(root.transform);
                var light2D = globalLight.AddComponent<Light2D>();
                light2D.lightType = Light2D.LightType.Global;
                light2D.intensity = 0.15f;
            }

            // Controller wiring
            var controllerGo = new GameObject("GalleryController");
            controllerGo.transform.SetParent(root.transform);
            var controller = controllerGo.AddComponent<GalleryController>();
            var so = new SerializedObject(controller);
            so.FindProperty("pageSet").objectReferenceValue = AssetDatabase.LoadAssetAtPath<GalleryPageSet>(
                GalleryRootPath + (is2D ? "GalleryPages_2D.asset" : "GalleryPages_3D.asset"));
            SerializedProperty anchorsProp = so.FindProperty("cellAnchors");
            anchorsProp.arraySize = 9;
            for (int i = 0; i < 9; i++) anchorsProp.GetArrayElementAtIndex(i).objectReferenceValue = anchors[i];
            so.FindProperty("postVolume").objectReferenceValue = volume;
            so.FindProperty("gridLines").objectReferenceValue = gridLines;
            so.FindProperty("inspectionLight").objectReferenceValue = inspectionLight;
            so.FindProperty("is2D").boolValue = is2D;
            so.ApplyModifiedPropertiesWithoutUndo();

            // Ambient: very dim so anything that emits is unmistakably self-lit (section 1.1).
            RenderSettings.ambientMode = AmbientMode.Flat;
            RenderSettings.ambientLight = new Color(0.06f, 0.065f, 0.08f);

            EditorSceneManager.SaveScene(scene, scenePath);
        }
    }
}
