using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using NUnit.Framework;
using UnityEngine;
using VFXComposer.Editor.Build;
using VFXComposer.Editor.Domain;
using VFXComposer.Editor.Workflow;

namespace VFXComposer.Tests.EditMode
{
    public sealed class VfxAiWorkflowExporterTests
    {
        [Test]
        public void GeneratedParameterTable_MatchesResolvedFormalCatalog_AndIsStable()
        {
            var first = VfxAiWorkflowExporter.ExportFormalCatalog();
            Assert.That(first.Report.HasErrors, Is.False, Describe(first));
            var committed = File.ReadAllText(first.OutputPath);
            Assert.That(committed, Is.EqualTo(first.Content), "The committed AI table must be exactly what the real Catalog exports.");

            var timestamp = File.GetLastWriteTimeUtc(first.OutputPath);
            var second = VfxAiWorkflowExporter.ExportFormalCatalog();
            Assert.That(second.Report.HasErrors, Is.False, Describe(second));
            Assert.That(second.Content, Is.EqualTo(first.Content));
            Assert.That(File.ReadAllText(second.OutputPath), Is.EqualTo(first.Content));
            Assert.That(File.GetLastWriteTimeUtc(second.OutputPath), Is.EqualTo(timestamp), "An unchanged export must not rewrite the file.");
            StringAssert.Contains("Do not edit this file by hand", committed);
            AssertExportUsesRawManifestTokens(committed);
        }

        [Test]
        public void GeneratedCanonicalRecipe_IsTheFormalDefault_AndPassesValidatorDryRunAndBuild()
        {
            var first = VfxAiWorkflowExporter.ExportCanonicalRecipe();
            Assert.That(first.Report.HasErrors, Is.False, Describe(first));
            Assert.That(File.ReadAllText(first.OutputPath), Is.EqualTo(first.Content));
            var timestamp = File.GetLastWriteTimeUtc(first.OutputPath);
            var second = VfxAiWorkflowExporter.ExportCanonicalRecipe();
            Assert.That(second.Report.HasErrors, Is.False, Describe(second));
            Assert.That(File.GetLastWriteTimeUtc(second.OutputPath), Is.EqualTo(timestamp), "An unchanged canonical export must not rewrite the file.");
            var canonical = File.ReadAllText(second.OutputPath);
            var parsed = VfxDomainParser.ParseRecipe(canonical);
            Assert.That(parsed.Report.HasErrors, Is.False, "Canonical JSON must remain a legal Recipe.");
            var build = new VfxCompiler().Build(canonical);
            Assert.That(build.Succeeded, Is.True, string.Join(" | ", build.Plan.Report.Entries.Select(entry => entry.Code + " " + entry.Path).ToArray()));
            StringAssert.Contains("\"id\": \"core\"", canonical);
            StringAssert.Contains("\"id\": \"trail\"", canonical);
            StringAssert.Contains("\"id\": \"embers\"", canonical);
        }

        [Test]
        public void GeneratedCanonicalPatches_AreStableBareArraysVerifiedByTheRealPatchService()
        {
            var first = VfxAiWorkflowExporter.ExportCanonicalPatches();
            Assert.That(first.Report.HasErrors, Is.False, Describe(first));
            var committed = File.ReadAllText(first.OutputPath); Assert.That(committed, Is.EqualTo(first.Content));
            var timestamp = File.GetLastWriteTimeUtc(first.OutputPath);
            var second = VfxAiWorkflowExporter.ExportCanonicalPatches();
            Assert.That(second.Report.HasErrors, Is.False, Describe(second));
            Assert.That(second.Content, Is.EqualTo(first.Content)); Assert.That(File.GetLastWriteTimeUtc(second.OutputPath), Is.EqualTo(timestamp), "An unchanged canonical Patch export must not rewrite the file.");
            StringAssert.Contains("## replace", committed); StringAssert.Contains("## disable", committed); StringAssert.Contains("## add", committed);
            StringAssert.Contains("\"op\": \"replace\"", committed); StringAssert.Contains("\"op\": \"disable\"", committed); StringAssert.Contains("\"op\": \"add\"", committed);
        }

        private static string Describe(VfxAiWorkflowExportResult result) { return string.Join(" | ", result.Report.Entries.ConvertAll(entry => entry.Code + " " + entry.Path + " " + entry.Message).ToArray()); }

        private static void AssertExportUsesRawManifestTokens(string markdown)
        {
            var root = Path.Combine(Application.dataPath, "VFX/Templates/2D/Manifests");
            foreach (var file in Directory.GetFiles(root, "*.json", SearchOption.AllDirectories).OrderBy(path => path, System.StringComparer.Ordinal))
            {
                var raw = File.ReadAllText(file);
                var templateId = StringValue(raw, "templateId");
                var kind = StringValue(raw, "kind");
                var dimension = StringValue(raw, "dimension");
                var matchingRows = markdown.Split('\n').Where(row => row.StartsWith("| " + templateId + " |", System.StringComparison.Ordinal)).ToArray();
                Assert.That(matchingRows, Is.Not.Empty, "Every resolved Manifest must have exported rows.");
                foreach (var row in matchingRows)
                {
                    StringAssert.Contains("| " + kind + " | " + dimension + " |", row, "Exported kind/dimension must be the formal JSON token, not a C# enum spelling.");
                }
            }
        }

        private static string StringValue(string json, string key)
        {
            var match = Regex.Match(json, "\\\"" + Regex.Escape(key) + "\\\"\\s*:\\s*\\\"(?<value>[^\\\"]*)\\\"");
            Assert.That(match.Success, Is.True, "Formal Manifest must contain string " + key);
            return match.Groups["value"].Value;
        }
    }
}
