using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Newtonsoft.Json.Linq;
using UnityEditor;
using UnityEngine;
using VFXComposer.Editor.Patch;
using VFXComposer.Editor.Domain;
using VFXComposer.Editor.Style;

namespace VFXComposer.Editor.UI
{
    public sealed class VfxStudioWindow : EditorWindow
    {
        private enum Tab{Library,Create,Preview,Patch,Review}
        private Tab tab;private List<VfxStudioLibraryItem> items=new List<VfxStudioLibraryItem>();private VfxStudioLibraryItem selected;private readonly VfxStudioLibraryFilter filter=new VfxStudioLibraryFilter();private readonly VfxStudioPatchQueue patchQueue=new VfxStudioPatchQueue();private readonly VfxStudioReviewState review=new VfxStudioReviewState();private Vector2 leftScroll,mainScroll;private string status="Ready.";private string description="";private string draftId="new_vfx_2d",draftName="New VFX",draftStyle="stylized",draftArchetype="projectile",draftDimension="2d",draftJson="";private int expectedRevision=1;private string reviewer="",archetypeParamName="rarity",archetypeParamValue="5";
        private string[] archetypes={"all"},dimensions={"all"},elements={"all"},styles={"all"},capabilities={"all"},carriers={"all"},lifecycles={"all"},maturities={"all"},productionStatuses={"all"};

        [MenuItem("Tools/VFX Composer/Studio")]
        public static void Open(){var window=GetWindow<VfxStudioWindow>("VFX Studio");window.minSize=new Vector2(1100,650);window.Show();}
        private void OnEnable(){Refresh();}
        private void OnGUI()
        {
            DrawTabs();EditorGUILayout.BeginHorizontal();DrawLeft();mainScroll=EditorGUILayout.BeginScrollView(mainScroll);ResolveActiveTabCallback()();EditorGUILayout.EndScrollView();EditorGUILayout.EndHorizontal();EditorGUILayout.Space();EditorGUILayout.HelpBox((selected==null?"No Recipe":selected.Id+" · "+selected.Archetype+" · "+selected.Dimension+" · "+selected.Style)+"\n"+status,MessageType.None);
        }
        private Action ResolveActiveTabCallback(){if(tab==Tab.Library)return DrawLibrary;if(tab==Tab.Create)return DrawCreate;if(tab==Tab.Preview)return DrawPreview;if(tab==Tab.Patch)return DrawPatch;return DrawReview;}
        // Batchmode cannot prove IMGUI pixels.  These internal seams exercise the exact production
        // refresh path and resolve (without invoking) the same Draw* callback used by OnGUI.
        internal static string[] IntegrationTabNamesForTests(){return Enum.GetNames(typeof(Tab));}
        internal string ResolveTabCallbackForIntegrationTests(string tabName){Tab value;if(!Enum.TryParse(tabName,false,out value)||!Enum.IsDefined(typeof(Tab),value))throw new ArgumentException("Unknown Studio tab.",nameof(tabName));var previous=tab;try{tab=value;return ResolveActiveTabCallback().Method.Name;}finally{tab=previous;}}
        internal int RefreshForIntegrationTests(){Refresh();return items.Count;}
        internal bool ContainsItemForIntegrationTests(string effectId){return items.Any(value=>value!=null&&string.Equals(value.Id,effectId,StringComparison.Ordinal));}
        private void DrawTabs(){EditorGUILayout.BeginHorizontal(EditorStyles.toolbar);foreach(Tab value in Enum.GetValues(typeof(Tab)))if(GUILayout.Toggle(tab==value,value.ToString(),EditorStyles.toolbarButton,GUILayout.Height(24)))tab=value;GUILayout.FlexibleSpace();if(GUILayout.Button("Refresh",EditorStyles.toolbarButton,GUILayout.Width(80)))Refresh();EditorGUILayout.EndHorizontal();}
        private void DrawLeft()
        {
            EditorGUILayout.BeginVertical(GUILayout.Width(285));filter.Search=EditorGUILayout.TextField("Search",filter.Search);filter.Archetype=Popup("Archetype",filter.Archetype,archetypes);filter.Dimension=Popup("Dimension",filter.Dimension,dimensions);filter.Element=Popup("Element",filter.Element,elements);filter.Style=Popup("Style",filter.Style,styles);filter.Capability=Popup("Capability",filter.Capability,capabilities);filter.Carrier=Popup("Carrier",filter.Carrier,carriers);filter.Lifecycle=Popup("Lifecycle",filter.Lifecycle,lifecycles);filter.Maturity=Popup("Maturity",filter.Maturity,maturities);filter.ProductionStatus=Popup("Status",filter.ProductionStatus,productionStatuses);leftScroll=EditorGUILayout.BeginScrollView(leftScroll);foreach(var item in items.Where(filter.Matches)){var label=item.Id+"\n"+item.Archetype+" · "+item.Dimension+" · "+item.Style+"\n"+item.ProductionStatus+" · "+item.Maturity;if(GUILayout.Toggle(selected==item,label,"Button",GUILayout.Height(62))&&selected!=item)SelectItem(item);}EditorGUILayout.EndScrollView();EditorGUILayout.EndVertical();
        }
        private void DrawLibrary(){Title("Library");EditorGUILayout.LabelField(items.Count+" Recipe families indexed from Recipes + ownership Manifests. W24 data is read-only.");if(selected==null)return;EditorGUILayout.Space();EditorGUILayout.LabelField(selected.Id,EditorStyles.boldLabel);Field("Recipe/source",selected.SourceRecipePath);Field("Runtime Entry",selected.RuntimeEntryPath??"not built");Field("Manifest / ownership",selected.ManifestPath+" · "+(selected.OwnershipSummary??"not verified"));Field("Enforcement",selected.Strict?"strict":"legacy_audit");Field("Contract",Identity(selected.ContractPath,selected.ContractFileHash,selected.ContractHash,selected.ContractRevision));Field("Trace",Identity(selected.TracePath,selected.TraceFileHash,null,0));Field("Evidence corpus",Identity(selected.EvidenceCorpusPath,null,selected.EvidenceCorpusHash,0));Field("User-verdict record",Identity(selected.UserVerdictRecordPath,selected.UserVerdictRecordHash,null,0));Field("Carrier(s)",Join(selected.Carriers));Field("Lifecycle",selected.Lifecycle);Field("Maturity",selected.Maturity);Field("Working status",selected.ProductionStatus);Field("Build / capture",Join(new[]{selected.BuildHash,selected.CaptureProfileHash}));EditorGUILayout.LabelField("Cost","GO "+selected.GameObjects+" / Renderer "+selected.Renderers+" / Local Material "+selected.Materials);EditorGUILayout.Space();EditorGUILayout.LabelField("Reasons",EditorStyles.boldLabel);foreach(var reason in selected.StatusReasons)EditorGUILayout.HelpBox(reason,MessageType.Info);DrawW24Details(selected);EditorGUILayout.BeginHorizontal();if(GUILayout.Button("Ping Recipe"))Ping(selected.RecipePath);if(GUILayout.Button("Ping Runtime Entry")&&!string.IsNullOrEmpty(selected.PrefabPath))Ping(selected.PrefabPath);if(GUILayout.Button("Use as Create Base")){tab=Tab.Create;draftId=selected.Id+"_variant";draftName=selected.Name+" Variant";draftStyle=selected.Style;}if(GUILayout.Button("Preview")){tab=Tab.Preview;OpenPreview();}EditorGUILayout.EndHorizontal();}
        private void DrawCreate(){Title("Create");EditorGUILayout.HelpBox("AI chat remains out of scope. Recipe drafts are not formal production records; no contract JSON can be pasted into Studio to bypass S5. Studio does not write new Recipes: formal creation must begin with an S5-approved plan.",MessageType.Info);description=EditorGUILayout.TextField("Description",description,GUILayout.Height(42));draftId=EditorGUILayout.TextField("ID",draftId);draftName=EditorGUILayout.TextField("Name",draftName);draftArchetype=EditorGUILayout.TextField("Archetype",draftArchetype);draftDimension=EditorGUILayout.TextField("Dimension",draftDimension);draftStyle=EditorGUILayout.TextField("Style",draftStyle);EditorGUILayout.BeginHorizontal();if(GUILayout.Button("Copy AI Prompt")){EditorGUIUtility.systemCopyBuffer=VfxStudioDraftBuilder.Prompt(description,draftArchetype,draftDimension,draftStyle,filter.Capability);status="Prompt copied; external AI must return raw Recipe JSON.";}using(new EditorGUI.DisabledScope(selected==null)){if(GUILayout.Button("Create Draft from Selected")){draftJson=VfxStudioDraftBuilder.FromRecipe(File.ReadAllText(Absolute(selected.RecipePath)),draftId,draftName,draftStyle,draftDimension,draftArchetype);status="Draft created in memory; no asset has been written.";}}EditorGUILayout.EndHorizontal();draftJson=EditorGUILayout.TextArea(draftJson,GUILayout.MinHeight(300));EditorGUILayout.BeginHorizontal();if(GUILayout.Button("Validate / Dry Run"))ValidateDraft();if(GUILayout.Button("Copy Draft JSON"))CopyDraft();if(GUILayout.Button("Formal Build (S5)"))FormalBuild();EditorGUILayout.EndHorizontal();}
        private void DrawPreview(){Title("Preview");if(selected==null){EditorGUILayout.HelpBox("Select a Library item.",MessageType.Info);return;}EditorGUILayout.LabelField("Selected",selected.Id);Field("Authoritative scene",selected.Contract==null||selected.Contract.CaptureProfile==null?"missing":selected.Contract.CaptureProfile.SceneSerializedReference);Field("Scene hash",selected.Contract==null||selected.Contract.CaptureProfile==null?"missing":selected.Contract.CaptureProfile.SceneHash);EditorGUILayout.HelpBox("Studio opens or plays only after validating the exact contract scene, capture manifest identity, build binding, and Runtime Entry. It never substitutes a gallery camera, generic sampler, or alternative evidence camera.",MessageType.Info);EditorGUILayout.BeginHorizontal();if(GUILayout.Button("Open Authoritative Scene"))OpenPreview();if(GUILayout.Button(EditorApplication.isPlaying?"Exit Play Mode":"Enter Authoritative Play Mode"))ToggleAuthoritativePlay();if(GUILayout.Button("Ping Runtime Entry")&&!string.IsNullOrEmpty(selected.PrefabPath))Ping(selected.PrefabPath);EditorGUILayout.EndHorizontal();EditorGUILayout.Space();EditorGUILayout.LabelField("Preview is operational only and never creates machine, QA, user-verdict, L3, or L4 status.");}
        private void DrawPatch(){Title("Patch");if(selected==null){EditorGUILayout.HelpBox("Select a Recipe first.",MessageType.Info);return;}EditorGUILayout.HelpBox("Studio can validate/copy a patch, but applying or writing it here is blocked until a formal post-patch S5 build plan supplies a newly bound contract, trace, build, capture and evidence corpus. This UI never rewrites formal bindings.",MessageType.Warning);expectedRevision=EditorGUILayout.IntField("Expected Revision",expectedRevision);EditorGUILayout.BeginHorizontal();if(GUILayout.Button("Style: Cartoon"))patchQueue.SetStyle("cartoon");if(GUILayout.Button("Style: Neon"))patchQueue.SetStyle("neon");if(GUILayout.Button("Style: Dark"))patchQueue.SetStyle("dark");EditorGUILayout.EndHorizontal();EditorGUILayout.BeginHorizontal();if(GUILayout.Button("Primary Cyan"))patchQueue.SetPalette("primary","#00D9FF");if(GUILayout.Button("Secondary White"))patchQueue.SetPalette("secondary","#F4FFFF");if(GUILayout.Button("Clear Queue"))patchQueue.Clear();EditorGUILayout.EndHorizontal();EditorGUILayout.BeginHorizontal();archetypeParamName=EditorGUILayout.TextField("Archetype parameter",archetypeParamName);archetypeParamValue=EditorGUILayout.TextField("JSON value",archetypeParamValue);if(GUILayout.Button("Queue semantic value",GUILayout.Width(160)))QueueArchetypeParameter();EditorGUILayout.EndHorizontal();EditorGUILayout.LabelField("Queued bare Patch JSON",EditorStyles.boldLabel);EditorGUILayout.TextArea(patchQueue.ToJson(),GUILayout.MinHeight(260));EditorGUILayout.BeginHorizontal();if(GUILayout.Button("Validate"))ValidatePatch();if(GUILayout.Button("Copy Patch JSON"))CopyPatch();if(GUILayout.Button("Apply through formal pipeline"))ApplyPatch();EditorGUILayout.EndHorizontal();}
        private void QueueArchetypeParameter(){if(string.IsNullOrWhiteSpace(archetypeParamName))return;JToken value;try{value=JToken.Parse(archetypeParamValue);}catch{value=new JValue(archetypeParamValue);}patchQueue.SetArchetypeParameter(archetypeParamName,value);}
        private void DrawReview(){Title("Review");if(selected==null){EditorGUILayout.HelpBox("Select a Recipe first.",MessageType.Info);return;}EditorGUILayout.HelpBox("Machine evidence, Visual QA evidence, and a user verdict are distinct. This Studio has no signing or migration-decision control; VISUAL_PENDING remains read-only until the assembly-internal authority verifies an exact persisted verdict.",MessageType.Warning);Field("Machine route",selected.MachineGate);Field("Visual QA route",selected.VisualQa);Field("User verdict",selected.UserVerdict);if(GUILayout.Button("Run automatic checks"))RunReviewChecks();using(new EditorGUI.DisabledScope(true)){review.Schema=EditorGUILayout.ToggleLeft("Schema",review.Schema);review.RuntimeEntry=EditorGUILayout.ToggleLeft("Runtime Entry",review.RuntimeEntry);review.Manifest=EditorGUILayout.ToggleLeft("Ownership Manifest",review.Manifest);review.StrictBudget=EditorGUILayout.ToggleLeft("Strict budget (pending S5 verifier)",review.StrictBudget);review.Idempotence=EditorGUILayout.ToggleLeft("Idempotence (pending S5 verifier)",review.Idempotence);review.PlaybackReset=EditorGUILayout.ToggleLeft("Playback / Stop / Reset (pending S5 verifier)",review.PlaybackReset);review.Evidence=EditorGUILayout.ToggleLeft("Evidence set",review.Evidence);}EditorGUILayout.Space();EditorGUILayout.LabelField("Review notes (not an L4 verdict)",EditorStyles.boldLabel);review.Shape=EditorGUILayout.ToggleLeft("Shape",review.Shape);review.Layers=EditorGUILayout.ToggleLeft("Layers",review.Layers);review.Motion=EditorGUILayout.ToggleLeft("Motion",review.Motion);review.Dissipation=EditorGUILayout.ToggleLeft("Dissipation",review.Dissipation);review.Depth=EditorGUILayout.ToggleLeft("Depth / composition",review.Depth);reviewer=EditorGUILayout.TextField("Reviewer",reviewer);using(new EditorGUI.DisabledScope(!review.AutomaticComplete||!review.ManualComplete||string.IsNullOrWhiteSpace(reviewer))){if(GUILayout.Button("Write review evidence (not sign-off)…"))WriteReview();}if(!review.ManualComplete)EditorGUILayout.HelpBox("VISUAL_PENDING. Review checkboxes do not create QA pass, a user verdict, L3, or L4.",MessageType.Warning);}
        private void Refresh(){items=VfxStudioLibrary.Scan();archetypes=VfxStudioLibrary.Values(items,value=>value.Archetype);dimensions=VfxStudioLibrary.Values(items,value=>value.Dimension);elements=VfxStudioLibrary.Values(items,value=>value.Element);styles=VfxStudioLibrary.Values(items,value=>value.Style);capabilities=new[]{"all"}.Concat(items.SelectMany(value=>value.Capabilities).Distinct(StringComparer.Ordinal).OrderBy(value=>value,StringComparer.Ordinal)).ToArray();carriers=new[]{"all"}.Concat(items.SelectMany(value=>value.Carriers??new string[0]).Distinct(StringComparer.Ordinal).OrderBy(value=>value,StringComparer.Ordinal)).ToArray();lifecycles=VfxStudioLibrary.Values(items,value=>value.Lifecycle);maturities=VfxStudioLibrary.Values(items,value=>value.Maturity);productionStatuses=VfxStudioLibrary.Values(items,value=>value.ProductionStatus);if(selected!=null)SelectItem(items.FirstOrDefault(value=>value.Id==selected.Id));status="Library refreshed: "+items.Count+" entries. VISUAL_PENDING is the conservative default.";}
        private void SelectItem(VfxStudioLibraryItem item){selected=item;review.Reset();reviewer=string.Empty;status="Selection changed; all review state reset to pending.";}
        private void ValidateDraft(){try{var parsed=VfxDomainParser.ParseRecipe(draftJson);var plan=new VFXComposer.Editor.SlashV2.S12CompilerDispatcher().DryRun(draftJson);status=(parsed.Report.HasErrors||plan.IsBlocked?"BLOCKED":"VALID")+"\n"+string.Join("\n",plan.Report.Entries.Select(value=>value.Code+" "+value.Path+" "+value.Message))+"\n\n"+VfxStudioProductionGatePresenter.EvaluateCurrent(selected);}catch(Exception e){status="BLOCKED: "+e.Message;}}
        private void FormalBuild(){status="Studio never builds from raw draft JSON. Formal Build requires an approved S5 plan with persisted contract and trace bindings.\n\n"+VfxStudioProductionGatePresenter.EvaluateCurrent(selected);}
        private void CopyDraft(){if(string.IsNullOrWhiteSpace(draftJson)){status="No draft.";return;}try{var parsed=VfxDomainParser.ParseRecipe(draftJson);if(parsed.Report.HasErrors){status="Copy blocked: invalid Recipe.";return;}EditorGUIUtility.systemCopyBuffer=draftJson;status="Draft JSON copied. Studio did not write a Recipe; formal creation requires an S5-approved plan.";}catch(Exception e){status="Copy blocked: "+e.Message;}}
        private void OpenPreview(){if(selected==null)return;string value;VfxStudioAuthoritativePreview.TryOpen(selected,out value);status=value;}
        private void ToggleAuthoritativePlay(){if(EditorApplication.isPlaying){EditorApplication.isPlaying=false;return;}if(selected==null)return;string value;if(!VfxStudioAuthoritativePreview.TryOpen(selected,out value)){status=value;return;}EditorApplication.isPlaying=true;status=value+"\nEntered Play Mode only after the authoritative preview guard passed.";}
        private void ValidatePatch(){if(selected==null||patchQueue.Count==0)return;var text=File.ReadAllText(Absolute(selected.RecipePath));var value=new VfxPatchService().Validate(text,patchQueue.ToJson(),expectedRevision);status=(value.IsValid?"VALID":"BLOCKED")+"\n"+string.Join("\n",value.Report.Entries.Select(item=>item.Code+" "+item.Path+" "+item.Message));}
        private void ApplyPatch(){if(selected==null||patchQueue.Count==0)return;status="Studio Patch apply is blocked. A patch changes the exact build/capture/evidence binding and must enter the formal S5 production pipeline with a new approved build plan.\n\n"+VfxStudioProductionGatePresenter.EvaluateCurrent(selected);}
        private void CopyPatch(){if(selected==null||patchQueue.Count==0)return;EditorGUIUtility.systemCopyBuffer=patchQueue.ToJson();status="Bare Patch JSON copied. Studio did not write or apply a patch; formal mutation requires an S5-approved plan.";}
        private void RunReviewChecks(){if(selected==null)return;try{var json=File.ReadAllText(Absolute(selected.RecipePath));var parsed=VfxDomainParser.ParseRecipe(json);var runtimeEntry=!string.IsNullOrEmpty(selected.PrefabPath)&&string.Equals(selected.PrefabPath,selected.RuntimeEntryPath,StringComparison.Ordinal)&&AssetDatabase.LoadAssetAtPath<GameObject>(selected.PrefabPath)!=null;var automatic=VfxStudioAutomaticReviewChecks.Evaluate(selected,!parsed.Report.HasErrors,runtimeEntry,File.Exists(selected.ManifestPath),false);review.Schema=automatic.Schema;review.RuntimeEntry=automatic.RuntimeEntry;review.Manifest=automatic.Manifest;review.StrictBudget=automatic.StrictBudget;review.Idempotence=automatic.Idempotence;review.PlaybackReset=automatic.PlaybackReset;review.Evidence=automatic.Evidence;status="Automatic review complete. Manifest/Trace claims are not budget, idempotence, or playback/reset verification; all three remain pending until the S5 byte-level verifier is reused. Evidence means only that declared bytes verify; manual visual boxes remain untouched.";}catch(Exception e){status="Review failed: "+e.Message;}}
        private void WriteReview(){var folder=Path.GetFullPath(Path.Combine(Application.dataPath,"..","..","docs","vfx-reviews",selected.Id));if(!EditorUtility.DisplayDialog("Write review evidence?","This records review notes for "+selected.Id+". It cannot create machine pass, QA pass, a user verdict, L3/L4, migration approval, or a commercial claim.","Write","Cancel"))return;Directory.CreateDirectory(folder);File.WriteAllText(Path.Combine(folder,"REVIEW.md"),review.ToMarkdown(selected.Id,reviewer),new UTF8Encoding(false));status="Wrote non-authoritative review notes; VISUAL_PENDING remains.";}
        private static void Field(string label,string value){EditorGUILayout.LabelField(label,value??"missing");}
        private static string Join(IEnumerable<string> values){var safe=(values??Enumerable.Empty<string>()).Where(value=>!string.IsNullOrEmpty(value)).ToArray();return safe.Length==0?"missing":string.Join(" · ",safe);}
        private static string Identity(string path,string fileHash,string canonicalHash,int revision){return Join(new[]{path,fileHash,canonicalHash,revision>0?"revision "+revision:null});}
        private static void DrawW24Details(VfxStudioLibraryItem item){if(item.Contract==null)return;EditorGUILayout.Space();EditorGUILayout.LabelField("Contract requirements",EditorStyles.boldLabel);foreach(var requirement in item.Contract.Requirements??new VFXComposer.Editor.W24.S1.VfxDesignRequirement[0]){var visual=requirement.VisualVerdict;EditorGUILayout.LabelField(requirement.DesignRequirementId+" · "+requirement.Type+" · authority="+requirement.EvidenceAuthority,EditorStyles.wordWrappedLabel);EditorGUILayout.LabelField("  "+requirement.Statement,EditorStyles.wordWrappedLabel);if(visual!=null&&visual.EvidenceLocation!=null)EditorGUILayout.LabelField("  visual location: "+visual.EvidenceLocation.State+" frames "+Join(visual.EvidenceLocation.FrameInterval.Select(value=>value.ToString()))+" ROI "+visual.EvidenceLocation.Roi,EditorStyles.wordWrappedLabel);}EditorGUILayout.LabelField("Layers / carriers",EditorStyles.boldLabel);foreach(var layer in item.Contract.Layers??new VFXComposer.Editor.W24.S1.VfxLayer[0])EditorGUILayout.LabelField(layer.LayerId+" · "+layer.Carrier+" · "+layer.Responsibility+" · "+layer.MotionModel,EditorStyles.wordWrappedLabel);EditorGUILayout.LabelField("Forbidden substitutions",EditorStyles.boldLabel);foreach(var substitution in item.Contract.ForbiddenSubstitutions??new VFXComposer.Editor.W24.S1.VfxSubstitution[0])EditorGUILayout.LabelField(substitution.From+" → "+substitution.To+" ("+substitution.Rationale+")",EditorStyles.wordWrappedLabel);if(item.Trace==null)return;EditorGUILayout.LabelField("UNVERIFIED Trace claims (S5 byte-level verifier not run)",EditorStyles.boldLabel);foreach(var trace in item.Trace.RequirementTraces??new VFXComposer.Editor.W24.S1.VfxRequirementTrace[0]){EditorGUILayout.LabelField(trace.DesignRequirementId+" · claimedAuthority="+trace.EvidenceAuthority+" · layers="+Join(trace.LayerIds),EditorStyles.wordWrappedLabel);foreach(var evidence in trace.AuthorityEvidence??new VFXComposer.Editor.W24.S1.VfxTraceEvidence[0])EditorGUILayout.LabelField("  UNVERIFIED authority claim: "+evidence.Kind+" · "+evidence.Reference+" · "+evidence.Sha256+" · claimedPassed="+evidence.Passed,EditorStyles.wordWrappedLabel);foreach(var evidence in trace.CrossEvidence??new VFXComposer.Editor.W24.S1.VfxTraceEvidence[0])EditorGUILayout.LabelField("  UNVERIFIED cross claim: "+evidence.Kind+" · "+evidence.Reference+" · "+evidence.Sha256+" · claimedPassed="+evidence.Passed,EditorStyles.wordWrappedLabel);}}
        private static void Title(string value){EditorGUILayout.LabelField(value,EditorStyles.boldLabel);EditorGUILayout.Space();}
        private static string Popup(string label,string value,string[] options){var index=Mathf.Max(0,Array.IndexOf(options,value));return options[EditorGUILayout.Popup(label,index,options)];}
        private static void Ping(string path){var asset=AssetDatabase.LoadAssetAtPath<UnityEngine.Object>(path);Selection.activeObject=asset;EditorGUIUtility.PingObject(asset);}
        private static string Absolute(string assetPath){return Path.GetFullPath(Path.Combine(Directory.GetParent(Application.dataPath).FullName,assetPath.Replace('/',Path.DirectorySeparatorChar)));}
    }
}
