using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace VFXComposer.Editor.W24.S1
{
    // Exact editor model for the portable lowerCamel authority schema.
    [JsonObject(MemberSerialization.OptIn)]
    public sealed class VfxDesignContract
    {
        [JsonProperty("contractVersion")] public string ContractVersion;
        [JsonProperty("effectId")] public string EffectId;
        [JsonProperty("contractRevision")] public int ContractRevision;
        [JsonProperty("contractHash")] public string ContractHash;
        [JsonProperty("lifecycle")] public VfxLifecycle Lifecycle;
        [JsonProperty("references")] public VfxReference[] References = Array.Empty<VfxReference>();
        [JsonProperty("spatialContract")] public VfxSpatialContract SpatialContract;
        [JsonProperty("captureProfile")] public VfxCaptureContract CaptureProfile;
        [JsonProperty("semanticStateMachine")] public VfxSemanticStateMachine SemanticStateMachine;
        [JsonProperty("layers")] public VfxLayer[] Layers = Array.Empty<VfxLayer>();
        [JsonProperty("allowedSubstitutions")] public VfxSubstitution[] AllowedSubstitutions = Array.Empty<VfxSubstitution>();
        [JsonProperty("forbiddenSubstitutions")] public VfxSubstitution[] ForbiddenSubstitutions = Array.Empty<VfxSubstitution>();
        [JsonProperty("cleanup")] public VfxCleanupContract Cleanup;
        [JsonProperty("budget")] public VfxBudgetContract Budget;
        [JsonProperty("requirements")] public VfxDesignRequirement[] Requirements = Array.Empty<VfxDesignRequirement>();
        [JsonProperty("extensions")] public JObject Extensions;
        [JsonIgnore] internal string AuthorityCanonicalHash;
        public string ComputeContractHash() { return VfxDesignContractJson.ComputeContractHash(this); }
        public static VfxDesignContract FromJson(string json) { return VfxDesignContractJson.FromJson(json); }
    }

    [JsonObject(MemberSerialization.OptIn)] public sealed class VfxLifecycle { [JsonProperty("kind")] public string Kind; [JsonProperty("start")] public VfxLifecycleStage Start; [JsonProperty("steady")] public VfxLifecycleStage Steady; [JsonProperty("stop")] public VfxLifecycleStage Stop; [JsonProperty("interrupt")] public VfxLifecycleStage Interrupt; }
    [JsonObject(MemberSerialization.OptIn)] public sealed class VfxLifecycleStage { [JsonProperty("entryConditions")] public string[] EntryConditions = Array.Empty<string>(); [JsonProperty("deadlineSeconds")] public double DeadlineSeconds; [JsonProperty("completionConditions")] public string[] CompletionConditions = Array.Empty<string>(); }
    [JsonObject(MemberSerialization.OptIn)] public sealed class VfxReference { [JsonProperty("source")] public string Source; [JsonProperty("hash")] public string Hash; [JsonProperty("license")] public string License; [JsonProperty("assetUse")] public string AssetUse; [JsonProperty("roles")] public VfxReferenceRole[] Roles = Array.Empty<VfxReferenceRole>(); [JsonProperty("notRequired")] public string[] NotRequired = Array.Empty<string>(); }
    [JsonObject(MemberSerialization.OptIn)] public sealed class VfxReferenceRole { [JsonProperty("dimension")] public string Dimension; [JsonProperty("weight")] public double Weight; }
    [JsonObject(MemberSerialization.OptIn)] public sealed class VfxSpatialContract { [JsonProperty("coordinateSpace")] public string CoordinateSpace; [JsonProperty("origin")] public double[] Origin = Array.Empty<double>(); [JsonProperty("orientationEulerDegrees")] public double[] OrientationEulerDegrees = Array.Empty<double>(); [JsonProperty("visualAnchor")] public VfxAnchor VisualAnchor; [JsonProperty("designDimensions")] public VfxDimensions DesignDimensions; [JsonProperty("gameplayDistanceDimensions")] public VfxDimensions GameplayDistanceDimensions; }
    [JsonObject(MemberSerialization.OptIn)] public sealed class VfxAnchor { [JsonProperty("kind")] public string Kind; [JsonProperty("reference")] public string Reference; }
    [JsonObject(MemberSerialization.OptIn)] public sealed class VfxDimensions { [JsonProperty("width")] public double Width; [JsonProperty("height")] public double Height; [JsonProperty("depth")] public double Depth; [JsonProperty("unit")] public string Unit; }
    [JsonObject(MemberSerialization.OptIn)] public sealed class VfxCaptureContract { [JsonProperty("captureProfileId")] public string CaptureProfileId; [JsonProperty("unityVersion")] public string UnityVersion; [JsonProperty("urpVersion")] public string UrpVersion; [JsonProperty("graphicsApi")] public string GraphicsApi; [JsonProperty("graphicsDeviceDriver")] public string GraphicsDeviceDriver; [JsonProperty("cameraSerializedReference")] public string CameraSerializedReference; [JsonProperty("cameraPose")] public VfxCameraPose CameraPose; [JsonProperty("cameraFovDegrees")] public double CameraFovDegrees; [JsonProperty("sceneSerializedReference")] public string SceneSerializedReference; [JsonProperty("sceneHash")] public string SceneHash; [JsonProperty("prefabManifestSerializedReference")] public string PrefabManifestSerializedReference; [JsonProperty("prefabManifestHash")] public string PrefabManifestHash; [JsonProperty("rendererAssetSerializedReference")] public string RendererAssetSerializedReference; [JsonProperty("volumeSerializedReference")] public string VolumeSerializedReference; [JsonProperty("resolution")] public VfxResolution Resolution; [JsonProperty("fps")] public int Fps; [JsonProperty("background")] public string Background; [JsonProperty("colorSpace")] public string ColorSpace; [JsonProperty("hdr")] public bool Hdr; [JsonProperty("msaaSamples")] public int MsaaSamples; [JsonProperty("renderTextureFormat")] public string RenderTextureFormat; [JsonProperty("bloom")] public VfxBloomContract Bloom; [JsonProperty("toneMapping")] public string ToneMapping; [JsonProperty("captureToolVersion")] public string CaptureToolVersion; [JsonProperty("captureToolHash")] public string CaptureToolHash; [JsonProperty("canonicalSeed")] public uint CanonicalSeed; [JsonProperty("robustnessSeeds")] public uint[] RobustnessSeeds = Array.Empty<uint>(); }
    [JsonObject(MemberSerialization.OptIn)] public sealed class VfxCameraPose { [JsonProperty("position")] public double[] Position = Array.Empty<double>(); [JsonProperty("orientationEulerDegrees")] public double[] OrientationEulerDegrees = Array.Empty<double>(); }
    [JsonObject(MemberSerialization.OptIn)] public sealed class VfxResolution { [JsonProperty("width")] public int Width; [JsonProperty("height")] public int Height; }
    [JsonObject(MemberSerialization.OptIn)] public sealed class VfxBloomContract { [JsonProperty("enabled")] public bool Enabled; [JsonProperty("settingsReference")] public string SettingsReference; }
    [JsonObject(MemberSerialization.OptIn)] public sealed class VfxSemanticStateMachine { [JsonProperty("deterministicForSameSeed")] public bool DeterministicForSameSeed; [JsonProperty("states")] public VfxSemanticState[] States = Array.Empty<VfxSemanticState>(); [JsonProperty("transitions")] public VfxTransition[] Transitions = Array.Empty<VfxTransition>(); [JsonProperty("completionExits")] public string[] CompletionExits = Array.Empty<string>(); [JsonProperty("interruptExits")] public string[] InterruptExits = Array.Empty<string>(); }
    [JsonObject(MemberSerialization.OptIn)] public sealed class VfxSemanticState { [JsonProperty("stateId")] public string StateId; [JsonProperty("role")] public string Role; [JsonProperty("durationSeconds")] public double DurationSeconds; [JsonProperty("entryConditions")] public string[] EntryConditions = Array.Empty<string>(); [JsonProperty("exitConditions")] public string[] ExitConditions = Array.Empty<string>(); [JsonProperty("triggeredEvents")] public string[] TriggeredEvents = Array.Empty<string>(); [JsonProperty("preservedSemantics")] public string[] PreservedSemantics = Array.Empty<string>(); }
    [JsonObject(MemberSerialization.OptIn)] public sealed class VfxTransition { [JsonProperty("from")] public string From; [JsonProperty("to")] public string To; [JsonProperty("continuityMode")] public string ContinuityMode; [JsonProperty("preservedSemantics")] public string[] PreservedSemantics = Array.Empty<string>(); [JsonProperty("triggeredEvents")] public string[] TriggeredEvents = Array.Empty<string>(); }
    [JsonObject(MemberSerialization.OptIn)] public sealed class VfxLayer { [JsonProperty("layerId")] public string LayerId; [JsonProperty("responsibility")] public string Responsibility; [JsonProperty("carrier")] public string Carrier; [JsonProperty("geometry")] public string Geometry; [JsonProperty("materialModel")] public string MaterialModel; [JsonProperty("colorRole")] public string ColorRole; [JsonProperty("blendMode")] public string BlendMode; [JsonProperty("motionModel")] public string MotionModel; [JsonProperty("timing")] public string Timing; [JsonProperty("attachment")] public string Attachment; [JsonProperty("continuityFrom")] public string[] ContinuityFrom = Array.Empty<string>(); [JsonProperty("continuityTo")] public string[] ContinuityTo = Array.Empty<string>(); [JsonProperty("budgetCost")] public JObject BudgetCost; [JsonProperty("required")] public bool Required; }
    [JsonObject(MemberSerialization.OptIn)] public sealed class VfxSubstitution { [JsonProperty("substitutionId")] public string SubstitutionId; [JsonProperty("from")] public string From; [JsonProperty("to")] public string To; [JsonProperty("rationale")] public string Rationale; }
    [JsonObject(MemberSerialization.OptIn)] public sealed class VfxCleanupContract { [JsonProperty("cleanupDeadline")] public double CleanupDeadline; [JsonProperty("allowedResidualLayers")] public string[] AllowedResidualLayers = Array.Empty<string>(); [JsonProperty("lightStopDeadline")] public double LightStopDeadline; }
    [JsonObject(MemberSerialization.OptIn)] public sealed class VfxBudgetContract { [JsonProperty("particlePeak")] public int ParticlePeak; [JsonProperty("particleSteady")] public int ParticleSteady; [JsonProperty("rendererCount")] public int RendererCount; [JsonProperty("materialCount")] public int MaterialCount; [JsonProperty("lightCount")] public int LightCount; [JsonProperty("textureResidency")] public VfxTextureResidency TextureResidency; }
    [JsonObject(MemberSerialization.OptIn)] public sealed class VfxTextureResidency { [JsonProperty("localExclusiveMb")] public double LocalExclusiveMb; [JsonProperty("totalDependencyMb")] public double TotalDependencyMb; }
    [JsonObject(MemberSerialization.OptIn)] public sealed class VfxDesignRequirement { [JsonProperty("designRequirementId")] public string DesignRequirementId; [JsonProperty("type")] public string Type; [JsonProperty("evidenceAuthority")] public string EvidenceAuthority; [JsonProperty("statement")] public string Statement; [JsonProperty("visualVerdict")] public VfxVisualVerdict VisualVerdict; }
    [JsonObject(MemberSerialization.OptIn)] public sealed class VfxVisualVerdict { [JsonProperty("subject")] public string Subject; [JsonProperty("expectedCondition")] public string ExpectedCondition; [JsonProperty("evidenceLocation")] public VfxEvidenceLocation EvidenceLocation; }
    [JsonObject(MemberSerialization.OptIn)] public sealed class VfxEvidenceLocation { [JsonProperty("state")] public string State; [JsonProperty("frameInterval")] public int[] FrameInterval = Array.Empty<int>(); [JsonProperty("roi")] public string Roi; [JsonProperty("layerMask")] public string LayerMask; }

    public enum W24GateSeverity { Error, Warning }
    public sealed class W24GateIssue { public W24GateSeverity Severity; public string Code; public string Path; public string Message; }
    public sealed class W24GateReport
    {
        private readonly List<W24GateIssue> issues = new List<W24GateIssue>();
        public IReadOnlyList<W24GateIssue> Issues => issues;
        public bool HasErrors => issues.Any(issue => issue.Severity == W24GateSeverity.Error);
        internal void Error(string code,string path,string message){issues.Add(new W24GateIssue{Severity=W24GateSeverity.Error,Code=code,Path=path,Message=message});}
        internal void Warning(string code,string path,string message){issues.Add(new W24GateIssue{Severity=W24GateSeverity.Warning,Code=code,Path=path,Message=message});}
    }

    public static class VfxDesignContractJson
    {
        private static readonly JsonSerializerSettings Settings = new JsonSerializerSettings { MissingMemberHandling=MissingMemberHandling.Error, NullValueHandling=NullValueHandling.Ignore, Culture=CultureInfo.InvariantCulture, FloatParseHandling=FloatParseHandling.Decimal };
        public static VfxDesignContract FromJson(string json){var root=ParseStrictObject(json);VfxContractRequiredShape.Validate(root);var contract=root.ToObject<VfxDesignContract>(JsonSerializer.Create(Settings));var identity=(JObject)root.DeepClone();identity.Remove("contractHash");contract.AuthorityCanonicalHash=W24Hash.Sha256(Canonical(identity));return contract;}
        public static W24GateReport ValidateJson(string json,out VfxDesignContract contract){contract=null;var report=new W24GateReport();try{contract=FromJson(json);}catch(Exception e)when(e is JsonException||e is FormatException||e is OverflowException){report.Error("W24J001","$",e.Message);return report;}return VfxDesignContractValidator.Validate(contract);}
        public static string ComputeContractHash(VfxDesignContract contract){if(contract==null)throw new ArgumentNullException(nameof(contract));if(!string.IsNullOrEmpty(contract.AuthorityCanonicalHash))return contract.AuthorityCanonicalHash;var root=JObject.FromObject(contract,JsonSerializer.Create(Settings));root.Remove("contractHash");return W24Hash.Sha256(Canonical(root));}
        public static string ComputeContractHash(string json){var root=ParseStrictObject(json);root.Remove("contractHash");return W24Hash.Sha256(Canonical(root));}
        internal static JObject ParseStrictObject(string json)
        {
            var root=W24StrictJsonText.ParseObject(json,"Contract JSON");
            foreach(var value in root.DescendantsAndSelf().OfType<JValue>())
            {
                if(value.Type==JTokenType.Float)
                {
                    if(value.Value is double number&&(double.IsNaN(number)||double.IsInfinity(number)))throw new JsonSerializationException("Contract numbers must be finite decimals.");
                    if(value.Value is float single&&(float.IsNaN(single)||float.IsInfinity(single)))throw new JsonSerializationException("Contract numbers must be finite decimals.");
                }
            }
            return root;
        }
        private static string Canonical(JToken value){if(value is JObject obj){var sorted=new JObject();foreach(var property in obj.Properties().OrderBy(p=>p.Name,StringComparer.Ordinal))sorted.Add(property.Name,JToken.Parse(Canonical(property.Value)));return sorted.ToString(Formatting.None);}if(value is JArray array)return new JArray(array.Select(item=>JToken.Parse(Canonical(item)))).ToString(Formatting.None);return value.ToString(Formatting.None);}
    }

    // Json.NET enforces unknown members; this companion enforces every Schema-required member,
    // including required numeric/boolean fields whose CLR default could otherwise hide omission.
    internal static class VfxContractRequiredShape
    {
        public static void Validate(JObject root)
        {
            Keys(root,"$","contractVersion","effectId","contractRevision","contractHash","lifecycle","references","spatialContract","captureProfile","semanticStateMachine","layers","allowedSubstitutions","forbiddenSubstitutions","cleanup","budget","requirements");
            var lifecycle=Obj(root,"lifecycle","$");Keys(lifecycle,"lifecycle","kind","start","steady","stop","interrupt");foreach(var name in new[]{"start","steady","stop","interrupt"})Keys(Obj(lifecycle,name,"lifecycle"),"lifecycle."+name,"entryConditions","deadlineSeconds","completionConditions");
            foreach(var item in Arr(root,"references","$").Children<JObject>()){Keys(item,"references[]","source","hash","license","assetUse","roles","notRequired");foreach(var role in Arr(item,"roles","references[]").Children<JObject>())Keys(role,"references[].roles[]","dimension","weight");}
            var spatial=Obj(root,"spatialContract","$");Keys(spatial,"spatialContract","coordinateSpace","origin","orientationEulerDegrees","visualAnchor","designDimensions","gameplayDistanceDimensions");Keys(Obj(spatial,"visualAnchor","spatialContract"),"spatialContract.visualAnchor","kind","reference");foreach(var name in new[]{"designDimensions","gameplayDistanceDimensions"})Keys(Obj(spatial,name,"spatialContract"),"spatialContract."+name,"width","height","depth","unit");
            var capture=Obj(root,"captureProfile","$");Keys(capture,"captureProfile","captureProfileId","unityVersion","urpVersion","graphicsApi","graphicsDeviceDriver","cameraSerializedReference","cameraPose","cameraFovDegrees","sceneSerializedReference","sceneHash","prefabManifestSerializedReference","prefabManifestHash","rendererAssetSerializedReference","volumeSerializedReference","resolution","fps","background","colorSpace","hdr","msaaSamples","renderTextureFormat","bloom","toneMapping","captureToolVersion","captureToolHash","canonicalSeed","robustnessSeeds");Keys(Obj(capture,"cameraPose","captureProfile"),"captureProfile.cameraPose","position","orientationEulerDegrees");Keys(Obj(capture,"resolution","captureProfile"),"captureProfile.resolution","width","height");Keys(Obj(capture,"bloom","captureProfile"),"captureProfile.bloom","enabled","settingsReference");
            var machine=Obj(root,"semanticStateMachine","$");Keys(machine,"semanticStateMachine","deterministicForSameSeed","states","transitions","completionExits","interruptExits");foreach(var state in Arr(machine,"states","semanticStateMachine").Children<JObject>())Keys(state,"semanticStateMachine.states[]","stateId","role","durationSeconds","entryConditions","exitConditions","triggeredEvents","preservedSemantics");foreach(var transition in Arr(machine,"transitions","semanticStateMachine").Children<JObject>())Keys(transition,"semanticStateMachine.transitions[]","from","to","continuityMode","preservedSemantics","triggeredEvents");
            foreach(var layer in Arr(root,"layers","$").Children<JObject>()){Keys(layer,"layers[]","layerId","responsibility","carrier","geometry","materialModel","colorRole","blendMode","motionModel","timing","attachment","continuityFrom","continuityTo","budgetCost","required");Obj(layer,"budgetCost","layers[]");}
            foreach(var group in new[]{"allowedSubstitutions","forbiddenSubstitutions"})foreach(var item in Arr(root,group,"$").Children<JObject>())Keys(item,group+"[]","substitutionId","from","to","rationale");
            Keys(Obj(root,"cleanup","$"),"cleanup","cleanupDeadline","allowedResidualLayers","lightStopDeadline");var budget=Obj(root,"budget","$");Keys(budget,"budget","particlePeak","particleSteady","rendererCount","materialCount","lightCount","textureResidency");Keys(Obj(budget,"textureResidency","budget"),"budget.textureResidency","localExclusiveMb","totalDependencyMb");
            foreach(var requirement in Arr(root,"requirements","$").Children<JObject>()){Keys(requirement,"requirements[]","designRequirementId","type","evidenceAuthority","statement");var type=(string)requirement["type"];if(type=="visual-measurable"||type=="visual-semantic"){Keys(requirement,"requirements[]","visualVerdict");var verdict=Obj(requirement,"visualVerdict","requirements[]");Keys(verdict,"requirements[].visualVerdict","subject","expectedCondition","evidenceLocation");var location=Obj(verdict,"evidenceLocation","requirements[].visualVerdict");Keys(location,"requirements[].visualVerdict.evidenceLocation","state","frameInterval");if(location["roi"]==null&&location["layerMask"]==null)throw new JsonSerializationException("requirements[].visualVerdict.evidenceLocation requires roi or layerMask.");}}
        }
        private static void Keys(JObject value,string path,params string[] keys){foreach(var key in keys)if(value[key]==null)throw new JsonSerializationException(path+" is missing required property '"+key+"'.");}
        private static JObject Obj(JObject parent,string key,string path){var value=parent[key] as JObject;if(value==null)throw new JsonSerializationException(path+"."+key+" must be an object.");return value;}
        private static JArray Arr(JObject parent,string key,string path){var value=parent[key] as JArray;if(value==null)throw new JsonSerializationException(path+"."+key+" must be an array.");return value;}
    }

    public static class VfxDesignContractValidator
    {
        private static readonly Regex EffectId=new Regex("^[a-z][a-z0-9]*(?:_[a-z0-9]+)*$",RegexOptions.CultureInvariant);
        private static readonly Regex RequirementId=new Regex("^[A-Za-z0-9._-]+$",RegexOptions.CultureInvariant);
        private static readonly string[] RequirementTypes={"visual-measurable","visual-semantic","behavioral","structural","budget","user-signoff"};
        private static readonly string[] Authorities={"telemetry","diagnostic","visualQa","user"};
        public static W24GateReport Validate(VfxDesignContract c){var r=new W24GateReport();if(c==null){r.Error("W24C000","$","A design contract is required.");return r;}Required(r,c.ContractVersion,"contractVersion");if(string.IsNullOrEmpty(c.EffectId)||!EffectId.IsMatch(c.EffectId))r.Error("W24C001","effectId","effectId must be lower_snake_case.");if(c.ContractRevision<1)r.Error("W24C002","contractRevision","contractRevision must be >= 1.");if(!W24Hash.IsCanonical(c.ContractHash))r.Error("W24C003","contractHash","Canonical hash required.");else if(c.ContractHash!=c.ComputeContractHash())r.Error("W24C004","contractHash","Hash does not match canonical UTF-8 lowerCamel JSON with contractHash omitted.");Lifecycle(r,c.Lifecycle);References(r,c.References);Spatial(r,c.SpatialContract);Capture(r,c.CaptureProfile,c.Extensions);var states=StateMachine(r,c.SemanticStateMachine);Layers(r,c.Layers);Substitutions(r,c.AllowedSubstitutions,"allowedSubstitutions",false);Substitutions(r,c.ForbiddenSubstitutions,"forbiddenSubstitutions",true);CleanupBudget(r,c.Cleanup,c.Budget,c.Layers);Requirements(r,c.Requirements,states,c.Layers);return r;}
        private static void Lifecycle(W24GateReport r,VfxLifecycle x){if(x==null){r.Error("W24C010","lifecycle","Required.");return;}if(!new[]{"sustained","one_shot","event_driven"}.Contains(x.Kind))r.Error("W24C011","lifecycle.kind","kind must be sustained, one_shot, or event_driven.");Stage(r,x.Start,"start");Stage(r,x.Steady,"steady");Stage(r,x.Stop,"stop");Stage(r,x.Interrupt,"interrupt");}
        private static void Stage(W24GateReport r,VfxLifecycleStage x,string p){if(x==null||!AnyText(x.EntryConditions)||!AnyText(x.CompletionConditions)||x.DeadlineSeconds<0)r.Error("W24C012","lifecycle."+p,"Stage needs conditions and nonnegative deadline.");}
        private static void References(W24GateReport r,VfxReference[] values){if(values==null){r.Error("W24C020","references","Array required.");return;}foreach(var x in values){if(x==null){r.Error("W24C021","references","Null reference.");continue;}Required(r,x.Source,"references.source");Hash(r,x.Hash,"references.hash");Required(r,x.License,"references.license");if(x.AssetUse!="reference-only"&&x.AssetUse!="may-use-as-asset")r.Error("W24C022","references.assetUse","Invalid.");if(x.Roles==null||x.Roles.Length==0||x.Roles.Any(v=>v==null||!new[]{"composition","colour","material","motion","atmosphere","attachment","lighting","timing"}.Contains(v.Dimension)||v.Weight<0||v.Weight>1))r.Error("W24C023","references.roles","Invalid roles.");if(x.NotRequired==null)r.Error("W24C024","references.notRequired","Array required.");}}
        private static void Spatial(W24GateReport r,VfxSpatialContract x){if(x==null){r.Error("W24C030","spatialContract","Required.");return;}if(!new[]{"world","local","screen"}.Contains(x.CoordinateSpace)||!Vec3(x.Origin)||!Vec3(x.OrientationEulerDegrees))r.Error("W24C031","spatialContract","Space/vectors invalid.");if(x.VisualAnchor==null||!new[]{"world-origin","transform","socket","mesh","bone","screen"}.Contains(x.VisualAnchor.Kind)||string.IsNullOrEmpty(x.VisualAnchor.Reference))r.Error("W24C032","spatialContract.visualAnchor","Invalid.");Dims(r,x.DesignDimensions,"designDimensions");Dims(r,x.GameplayDistanceDimensions,"gameplayDistanceDimensions");}
        private static void Dims(W24GateReport r,VfxDimensions x,string p){if(x==null||x.Width<=0||x.Height<=0||x.Depth<0||string.IsNullOrEmpty(x.Unit))r.Error("W24C033","spatialContract."+p,"Invalid dimensions.");}
        private static void Capture(W24GateReport r,VfxCaptureContract x,JObject extensions){if(x==null){r.Error("W24C040","captureProfile","Required.");return;}foreach(var v in new[]{x.CaptureProfileId,x.UnityVersion,x.UrpVersion,x.GraphicsApi,x.GraphicsDeviceDriver,x.CameraSerializedReference,x.SceneSerializedReference,x.PrefabManifestSerializedReference,x.RendererAssetSerializedReference,x.VolumeSerializedReference,x.Background,x.ColorSpace,x.RenderTextureFormat,x.ToneMapping,x.CaptureToolVersion})if(string.IsNullOrEmpty(v)){r.Error("W24C041","captureProfile","Required string missing.");break;}var status=(string)extensions?["captureBindingStatus"];var pending=status=="PENDING_FIRST_FORMAL_BUILD";if(pending){if(x.SceneHash!="pending:formal-build"||x.PrefabManifestHash!="pending:formal-build")r.Error("W24C047","captureProfile","PENDING_FIRST_FORMAL_BUILD requires both content identities to use pending:formal-build.");}else{Hash(r,x.SceneHash,"captureProfile.sceneHash");Hash(r,x.PrefabManifestHash,"captureProfile.prefabManifestHash");if(IsZeroHash(x.SceneHash)||IsZeroHash(x.PrefabManifestHash))r.Error("W24C048","captureProfile","All-zero hashes are not content identities; use pending:formal-build before C0.");}Hash(r,x.CaptureToolHash,"captureProfile.captureToolHash");if(IsZeroHash(x.CaptureToolHash))r.Error("W24C048A","captureProfile.captureToolHash","Capture tool identity must bind a real registered bundle and may not be all-zero.");if(x.CameraPose==null||!Vec3(x.CameraPose.Position)||!Vec3(x.CameraPose.OrientationEulerDegrees)||x.CameraFovDegrees<=0||x.CameraFovDegrees>179)r.Error("W24C042","captureProfile.cameraPose","Invalid.");if(x.Resolution==null||x.Resolution.Width<1||x.Resolution.Height<1||x.Fps<1||!new[]{1,2,4,8}.Contains(x.MsaaSamples))r.Error("W24C043","captureProfile.resolution","Invalid.");if(x.Bloom==null||string.IsNullOrEmpty(x.Bloom.SettingsReference))r.Error("W24C044","captureProfile.bloom","Invalid.");if(x.ColorSpace!="Linear"&&x.ColorSpace!="Gamma")r.Error("W24C045","captureProfile.colorSpace","Invalid.");if(x.RobustnessSeeds==null||x.RobustnessSeeds.Length!=2||x.RobustnessSeeds.Distinct().Count()!=2||x.RobustnessSeeds.Contains(x.CanonicalSeed))r.Error("W24C046","captureProfile.robustnessSeeds","Need two unique non-canonical seeds.");}
        private static HashSet<string> StateMachine(W24GateReport r,VfxSemanticStateMachine x){var ids=new HashSet<string>(StringComparer.Ordinal);if(x==null){r.Error("W24C050","semanticStateMachine","Required.");return ids;}if(!x.DeterministicForSameSeed)r.Error("W24C051","semanticStateMachine.deterministicForSameSeed","Must be true.");foreach(var v in Safe(x.States)){if(v==null||string.IsNullOrEmpty(v.StateId)||!ids.Add(v.StateId)){r.Error("W24C052","semanticStateMachine.states","State ID invalid/duplicate.");continue;}if(!new[]{"start","steady","stop","interrupt","custom"}.Contains(v.Role)||v.DurationSeconds<0||!AnyText(v.EntryConditions)||!AnyText(v.ExitConditions)||v.TriggeredEvents==null||v.PreservedSemantics==null)r.Error("W24C053","semanticStateMachine.states."+v.StateId,"Invalid state.");}foreach(var role in new[]{"start","steady","stop","interrupt"})if(!Safe(x.States).Any(v=>v!=null&&v.Role==role))r.Error("W24C054","semanticStateMachine.states","Missing "+role+" role.");if(x.Transitions==null||x.Transitions.Length==0)r.Error("W24C055","semanticStateMachine.transitions","At least one transition is required.");foreach(var v in Safe(x.Transitions))if(v==null||!ids.Contains(v.From)||!ids.Contains(v.To)||!new[]{"continuous","impulse","replace","clear"}.Contains(v.ContinuityMode)||v.PreservedSemantics==null||v.TriggeredEvents==null)r.Error("W24C055","semanticStateMachine.transitions","Invalid transition.");if(!AnyText(x.CompletionExits)||!AnyText(x.InterruptExits))r.Error("W24C056","semanticStateMachine","Semantic exit descriptions required.");return ids;}
        private static void Layers(W24GateReport r,VfxLayer[] values){var ids=new HashSet<string>(StringComparer.Ordinal);if(values==null||values.Length==0){r.Error("W24C060","layers","At least one required.");return;}foreach(var x in values){if(x==null||string.IsNullOrEmpty(x.LayerId)||!ids.Add(x.LayerId)){r.Error("W24C061","layers","Layer ID invalid/duplicate.");continue;}if(new[]{x.Responsibility,x.Carrier,x.Geometry,x.MaterialModel,x.ColorRole,x.BlendMode,x.MotionModel,x.Timing,x.Attachment}.Any(string.IsNullOrEmpty)||x.ContinuityFrom==null||x.ContinuityTo==null||x.BudgetCost==null||!x.BudgetCost.Properties().Any())r.Error("W24C062","layers."+x.LayerId,"Carrier fields, semantic continuity arrays and budgetCost object required.");}}
        private static void Substitutions(W24GateReport r,VfxSubstitution[] values,string p,bool required){var ids=new HashSet<string>(StringComparer.Ordinal);if(values==null||required&&values.Length==0){r.Error("W24C070",p,"Missing or empty.");return;}foreach(var x in values)if(x==null||string.IsNullOrEmpty(x.SubstitutionId)||!ids.Add(x.SubstitutionId)||string.IsNullOrEmpty(x.From)||string.IsNullOrEmpty(x.To)||string.IsNullOrEmpty(x.Rationale))r.Error("W24C071",p,"Invalid substitution.");}
        private static void CleanupBudget(W24GateReport r,VfxCleanupContract c,VfxBudgetContract b,VfxLayer[] layers){if(c==null||c.CleanupDeadline<0||c.LightStopDeadline<0||c.AllowedResidualLayers==null)r.Error("W24C080","cleanup","Invalid.");else{var ids=new HashSet<string>(Safe(layers).Where(x=>x!=null).Select(x=>x.LayerId),StringComparer.Ordinal);if(c.AllowedResidualLayers.Distinct(StringComparer.Ordinal).Count()!=c.AllowedResidualLayers.Length)r.Error("W24C081","cleanup.allowedResidualLayers","Residual layers must be unique.");foreach(var id in c.AllowedResidualLayers)if(!ids.Contains(id))r.Error("W24C081","cleanup.allowedResidualLayers","Unknown residual layer.");}if(b==null||b.ParticlePeak<0||b.ParticleSteady<0||b.RendererCount<0||b.MaterialCount<0||b.LightCount<0||b.TextureResidency==null||b.TextureResidency.LocalExclusiveMb<0||b.TextureResidency.TotalDependencyMb<b.TextureResidency.LocalExclusiveMb)r.Error("W24C082","budget","Budget or nested textureResidency invalid.");}
        private static void Requirements(W24GateReport r,VfxDesignRequirement[] values,HashSet<string> states,VfxLayer[] layers){var ids=new HashSet<string>(StringComparer.Ordinal);if(values==null||values.Length==0){r.Error("W24C090","requirements","At least one required.");return;}foreach(var x in values){if(x==null||string.IsNullOrEmpty(x.DesignRequirementId)||!RequirementId.IsMatch(x.DesignRequirementId)||!ids.Add(x.DesignRequirementId)){r.Error("W24C091","requirements","ID invalid/duplicate.");continue;}if(!RequirementTypes.Contains(x.Type)||!Authorities.Contains(x.EvidenceAuthority)||string.IsNullOrEmpty(x.Statement))r.Error("W24C092","requirements."+x.DesignRequirementId,"Type/authority/statement invalid.");var expected=x.Type=="visual-measurable"?"diagnostic":x.Type=="visual-semantic"?"visualQa":x.Type=="user-signoff"?"user":"telemetry";if(x.EvidenceAuthority!=expected)r.Error("W24C093","requirements."+x.DesignRequirementId+".evidenceAuthority","Type requires "+expected+".");if(x.Type=="visual-measurable"||x.Type=="visual-semantic")Visual(r,x.VisualVerdict,"requirements."+x.DesignRequirementId+".visualVerdict",layers);}}
        private static void Visual(W24GateReport r,VfxVisualVerdict x,string p,VfxLayer[] layers){if(x==null||string.IsNullOrEmpty(x.Subject)||string.IsNullOrEmpty(x.ExpectedCondition)||x.EvidenceLocation==null){r.Error("W24C094",p,"Incomplete.");return;}var l=x.EvidenceLocation;if(string.IsNullOrEmpty(l.State)||l.FrameInterval==null||l.FrameInterval.Length!=2||l.FrameInterval[0]<0||l.FrameInterval[1]<l.FrameInterval[0]||string.IsNullOrEmpty(l.Roi)&&string.IsNullOrEmpty(l.LayerMask))r.Error("W24C095",p+".evidenceLocation","State description, frameInterval and ROI/layerMask required.");if(!string.IsNullOrEmpty(l.LayerMask)&&!Safe(layers).Any(v=>v!=null&&v.LayerId==l.LayerMask))r.Error("W24C096",p+".evidenceLocation.layerMask","Unknown layer.");}
        private static bool Vec3(double[] x){return x!=null&&x.Length==3&&x.All(v=>!double.IsNaN(v)&&!double.IsInfinity(v));}private static bool AnyText(string[] x){return x!=null&&x.Length>0&&x.All(v=>!string.IsNullOrEmpty(v));}private static bool IsZeroHash(string x){return x=="sha256:"+new string('0',64);}private static void Required(W24GateReport r,string x,string p){if(string.IsNullOrEmpty(x))r.Error("W24C100",p,"Required.");}private static void Hash(W24GateReport r,string x,string p){if(!W24Hash.IsCanonical(x))r.Error("W24C101",p,"Canonical SHA-256 required.");}private static IEnumerable<T> Safe<T>(IEnumerable<T> x){return x??Enumerable.Empty<T>();}
    }

    internal static class W24Hash
    {
        private static readonly Regex Canonical=new Regex("^sha256:[a-f0-9]{64}$",RegexOptions.CultureInvariant);
        public static bool IsCanonical(string value){return value!=null&&Canonical.IsMatch(value);}
        public static string Sha256(string value){using(var sha=SHA256.Create())return "sha256:"+string.Concat(sha.ComputeHash(Encoding.UTF8.GetBytes(value??string.Empty)).Select(b=>b.ToString("x2",CultureInfo.InvariantCulture)));}
    }
}
