using System;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using Newtonsoft.Json.Linq;
using UnityEditor;
using VFXComposer.Editor.SlashV2;

namespace VFXComposer.Editor.Workflow
{
    /// <summary>Machine-derived, dispatch-free S12 v2 AI contract export. This class never creates or calls an AI agent.</summary>
    public static class S12SlashAiExporter
    {
        public const string Root = "docs/ai-workflow/s12-slash-v3";
        public const string FrozenRoot = Root + "/frozen";
        [MenuItem("Tools/VFX Composer/AI Workflow/Export S12 Slash v2 Contract (no dispatch)")]
        public static void ExportFromMenu() { Export(); }
        public static S12SlashAiExport Export()
        {
            var catalog = S12SlashCompiler.LoadFormalCatalog(); if (catalog.Report.HasErrors) throw new InvalidOperationException("Cannot export S12 AI contract: formal Slash catalog is invalid.");
            var recipe = S12RecipeDispatcher.Parse(File.ReadAllText(Absolute("Assets/VFX/Recipes/Slash/slash-3d-stylized.default.v2.json"))).SlashV2;
            var phases = new JArray(recipe.Phases.Select(phase => { var module = phase.Modules.Single(); return new JObject { ["id"] = phase.Id, ["kind"] = phase.Kind, ["startTime"] = phase.StartTime, ["duration"] = phase.Duration, ["enabled"] = phase.Enabled, ["modules"] = new JArray(new JObject { ["id"] = module.Id, ["kind"] = module.Kind, ["templateId"] = module.TemplateId, ["enabled"] = module.Enabled, ["parameters"] = new JObject(module.Parameters.OrderBy(x => x.Key, StringComparer.Ordinal).Select(x => new JProperty(x.Key, x.Value.DeepClone()))) }) }; }));
            var declarations = new JObject(catalog.ByTemplateId.Values.OrderBy(x => x.TemplateId, StringComparer.Ordinal).Select(m => new JProperty(m.TemplateId, new JObject(m.Parameters.OrderBy(x => x.Key, StringComparer.Ordinal).Select(x => new JProperty(x.Key, new JObject { ["type"] = x.Value.Type, ["min"] = x.Value.Min, ["default"] = x.Value.Default, ["max"] = x.Value.Max }))))));
            var contract = new JObject { ["schema"] = "s12-slash-ai-contract/v2", ["runtimeEvidence"] = 0, ["recipeSkeleton"] = new JObject { ["recipeVersion"] = recipe.RecipeVersion, ["revision"] = recipe.Revision, ["id"] = recipe.Id, ["name"] = recipe.Name, ["dimension"] = recipe.Dimension, ["archetype"] = recipe.Archetype, ["targetProfile"] = recipe.TargetProfile, ["randomSeed"] = recipe.RandomSeed, ["timeline"] = new JObject { ["duration"] = recipe.Timeline.Duration }, ["metadata"] = new JObject { ["createdBy"] = recipe.Metadata.CreatedBy, ["templateCatalogVersion"] = recipe.Metadata.TemplateCatalogVersion }, ["phases"] = phases }, ["catalog"] = declarations, ["targetProfiles"] = new JArray("mobile_medium", "pc_editor"), ["budget"] = new JObject { ["particleSystemsMax"] = 4, ["materialsMax"] = 5, ["peakParticlesMax"] = 48, ["transparentRenderersMax"] = 7 }, ["patch"] = new JObject { ["topLevel"] = "bare-array", ["ops"] = new JArray("replace"), ["path"] = "/phases/{phaseId}/modules/{moduleId}/parameters/{parameter}", ["forbidden"] = new JArray("array-index", "add", "remove", "id", "kind", "templateId", "startTime", "duration", "enabled", "generic-particle", "projectile", "Launch-Travel-Impact") } };
            var root = Path.Combine(RepositoryRoot(), Root.Replace('/', Path.DirectorySeparatorChar)); var frozen = Path.Combine(RepositoryRoot(), FrozenRoot.Replace('/', Path.DirectorySeparatorChar)); if (File.Exists(Path.Combine(frozen, "manifest.generated.json"))) throw new InvalidOperationException("S12 AI contract is frozen; Export is intentionally write-blocked. Use VerifyExisting."); Directory.CreateDirectory(root); var contractText = contract.ToString(Newtonsoft.Json.Formatting.None); Write(Path.Combine(root, "contract.generated.json"), contractText);
            var acceptance = new JObject { ["runtimeEvidence"] = 0, ["recipe"] = new JObject { ["exact"] = new JObject { ["recipeVersion"] = 2, ["revision"] = 1, ["id"] = recipe.Id, ["dimension"] = "3d", ["archetype"] = "slash", ["targetProfile"] = recipe.TargetProfile }, ["phaseIds"] = new JArray(recipe.Phases.Select(x => x.Id)), ["operator"] = "equals-schema-and-manifest-ranges", ["requiredChanges"] = new JArray(new JObject { ["path"] = "/phases/primary_arc/modules/arc_sweep/parameters/width", ["comparison"] = "number > default && number <= max" }, new JObject { ["path"] = "/phases/sparks/modules/slash_sparks/parameters/count", ["comparison"] = "integer > default && integer <= max" }, new JObject { ["path"] = "/phases/afterimage/modules/arc_afterimage/parameters/alpha", ["comparison"] = "number > default && number <= 0.44" }) }, ["patches"] = new JArray(new JObject { ["name"] = "primaryWidth", ["op"] = "replace", ["path"] = "/phases/primary_arc/modules/arc_sweep/parameters/width", ["comparison"] = "number > default && number <= max" }, new JObject { ["name"] = "sparkCount", ["op"] = "replace", ["path"] = "/phases/sparks/modules/slash_sparks/parameters/count", ["comparison"] = "integer > default && integer <= max" }, new JObject { ["name"] = "afterimageAlpha", ["op"] = "replace", ["path"] = "/phases/afterimage/modules/arc_afterimage/parameters/alpha", ["comparison"] = "number > default && number <= 0.44" }) }; var acceptanceText = acceptance.ToString(Newtonsoft.Json.Formatting.None); Write(Path.Combine(root, "acceptance-spec.generated.json"), acceptanceText);
            var task = new[] { new { Name = "recipe", Prompt = "Raw JSON only; no tools/markdown/generic particle/projectile/LTI. Create the described lower-left-to-upper-right slash.", Acceptance = (JToken)new JObject { ["exact"] = acceptance["recipe"]["exact"], ["phaseIds"] = acceptance["recipe"]["phaseIds"], ["changes"] = acceptance["recipe"]["requiredChanges"] } }, new { Name = "patch-primary-width", Prompt = "Raw bare array only; no tools/markdown. Broaden primary arc with one replace.", Acceptance = ((JArray)acceptance["patches"])[0] }, new { Name = "patch-spark-count", Prompt = "Raw bare array only; no tools/markdown. Slightly increase sparse sparks with one replace.", Acceptance = ((JArray)acceptance["patches"])[1] }, new { Name = "patch-afterimage-alpha", Prompt = "Raw bare array only; no tools/markdown. Slightly strengthen subordinate afterimage with one replace.", Acceptance = ((JArray)acceptance["patches"])[2] } };
            foreach (var item in task) Write(Path.Combine(root, item.Name + ".payload.generated.json"), new JObject { ["task"] = item.Prompt, ["contract"] = contract, ["acceptance"] = item.Acceptance, ["runtimeEvidence"] = 0 }.ToString(Newtonsoft.Json.Formatting.None));
            var files = Directory.GetFiles(root, "*.generated.json").Where(path => !string.Equals(Path.GetFileName(path), "manifest.generated.json", StringComparison.Ordinal)).OrderBy(x => x, StringComparer.Ordinal).Select(path => new JObject { ["file"] = Path.GetFileName(path), ["sha256"] = Hash(File.ReadAllText(path)), ["bytes"] = new FileInfo(path).Length }); Write(Path.Combine(root, "manifest.generated.json"), new JObject { ["runtimeEvidence"] = 0, ["files"] = new JArray(files) }.ToString(Newtonsoft.Json.Formatting.None));
            return new S12SlashAiExport { ContractPath = Path.Combine(root, "contract.generated.json"), ContractHash = Hash(contractText), ContractBytes = Encoding.UTF8.GetByteCount(contractText), RuntimeEvidence = 0 };
        }
        [MenuItem("Tools/VFX Composer/AI Workflow/Freeze S12 Slash v2 Contract (no dispatch)")]
        public static void Freeze()
        {
            var root = Path.Combine(RepositoryRoot(), Root.Replace('/', Path.DirectorySeparatorChar)); var frozen = Path.Combine(RepositoryRoot(), FrozenRoot.Replace('/', Path.DirectorySeparatorChar)); if (Directory.Exists(frozen)) throw new InvalidOperationException("S12 AI contract was already frozen; it cannot be overwritten."); if (!File.Exists(Path.Combine(root, "manifest.generated.json"))) throw new InvalidOperationException("Export S12 AI contract before freezing."); Directory.CreateDirectory(frozen); foreach (var file in Directory.GetFiles(root, "*.generated.json")) File.Copy(file, Path.Combine(frozen, Path.GetFileName(file))); if (!VerifyExisting()) throw new InvalidOperationException("S12 AI freeze verification failed.");
        }
        [MenuItem("Tools/VFX Composer/AI Workflow/Verify frozen S12 Slash v2 Contract")]
        public static bool VerifyExisting()
        {
            var frozen = Path.Combine(RepositoryRoot(), FrozenRoot.Replace('/', Path.DirectorySeparatorChar)); var manifestPath = Path.Combine(frozen, "manifest.generated.json"); if (!File.Exists(manifestPath)) return false; try { var manifest = JObject.Parse(File.ReadAllText(manifestPath)); if ((int)manifest["runtimeEvidence"] != 0) return false; return ((JArray)manifest["files"]).Children<JObject>().All(x => { var path = Path.Combine(frozen, (string)x["file"]); return File.Exists(path) && new FileInfo(path).Length == (long)x["bytes"] && Hash(File.ReadAllText(path)) == (string)x["sha256"]; }); } catch { return false; }
        }
        private static void Write(string path, string text) { if (Encoding.UTF8.GetByteCount(text) >= 3500) throw new InvalidOperationException("S12 AI payload exceeds 3500 bytes: " + Path.GetFileName(path)); if (!File.Exists(path) || File.ReadAllText(path) != text) File.WriteAllText(path, text, new UTF8Encoding(false)); }
        private static string Absolute(string assetPath) { return Path.Combine(UnityEngine.Application.dataPath, assetPath.Substring("Assets/".Length)); }
        private static string RepositoryRoot() { return Directory.GetParent(Directory.GetParent(UnityEngine.Application.dataPath).FullName).FullName; }
        private static string Hash(string text) { using (var sha = SHA256.Create()) return string.Concat(sha.ComputeHash(Encoding.UTF8.GetBytes(text)).Select(x => x.ToString("X2"))); }
    }
    public sealed class S12SlashAiExport { public string ContractPath; public string ContractHash; public int ContractBytes; public int RuntimeEvidence; }
}
