using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using VFXComposer.Editor.Build;
using VFXComposer.Editor.Domain;
using VFXComposer.Editor.Rules;
using VFXComposer.Editor.Style;
using VFXComposer.Editor.Validation;

namespace VFXComposer.Editor.Composite
{
    public sealed class CompositePlanEntry
    {
        public string Id, Group, Dimension, Primary, Secondary, Accent, ThemeId, ShapeLanguage;
        public float Duration; public JArray Timeline, CameraHints, Gates;
    }

    public sealed class HeroExclusiveEntry
    {
        public string Id, Archetype, Dimension, Style, Primary, Secondary, Accent, Behavior;
        public float Duration;
    }

    public static class CompositeAndHeroKitCatalog
    {
        public static readonly CompositePlanEntry[] Ultimates =
        {
            C("dragon_breath_ultimate_3d","ultimate","3d",4f,"#FF491C","#FFB32F","#FFF3B0",T(
                E(0,"focus_charge_3d"),E(.8,"flamethrower_beam_3d",1.25f),E(1.3,"ember_rain_area_3d"),E(3.2,"fire_nova_burst_3d",1.3f)),H(Hint(.7,"zoom",.45),Hint(1,"shake",.55),Hint(3.2,"slowmo",.35))),
            C("meteor_shower_ultimate_3d","ultimate","3d",5f,"#D8491E","#FF9E31","#F2D0A2",T(
                E(0,"warning_telegraph_3d"),S(.9,"warning_telegraph_3d"),E(1,"meteor_impact_3d",1,Pos(-1.5f,.7f,0)),E(1.5,"meteor_impact_3d",.9f,Pos(.9f,.3f,0)),E(2,"meteor_impact_3d",1.2f,Pos(-.4f,-.3f,0)),E(2.5,"meteor_impact_3d",.85f,Pos(1.5f,-.5f,0)),E(3,"meteor_impact_3d",1.15f,Pos(.2f,.6f,0)),E(3.5,"meteor_impact_3d",1,Pos(-1,-.8f,0)),E(4.6,"smoke_plume_area_3d",1.35f)),H(Hint(.9,"zoom",.3),Hint(2,"shake",.7),Hint(3.5,"shake",.9))),
            C("frozen_domain_ultimate_3d","ultimate","3d",6f,"#2B8FD5","#8DE8FF","#F2FFFF",T(
                E(0,"focus_charge_3d"),E(.6,"blizzard_area_3d",1.35f),E(2.2,"flash_freeze_transform_3d",1.2f),E(4.8,"ice_spike_spawn_3d",1.45f)),H(Hint(.5,"zoom",.4),Hint(2.2,"slowmo",.65),Hint(4.8,"shake",.75))),
            C("judgement_ray_ultimate_3d","ultimate","3d",4f,"#E6B735","#FFF18A","#FFFFFF",T(
                E(0,"arcane_rune_spawn_2d",1.4f),E(.8,"focus_charge_3d"),E(1.8,"divine_smite_impact_3d",1.6f),E(2.9,"resurrection_spawn_3d",.72f)),H(Hint(1.7,"slowmo",.45),Hint(1.8,"shake",.8),Hint(2,"zoom",.55))),
            C("demon_gate_boss_3d","ultimate","3d",8f,"#3A0711","#8E1730","#ED473F",T(
                E(0,"blood_ritual_spawn_3d",1.3f),E(1.2,"rift_spawn_3d",1.5f),E(4.2,"demon_eruption_impact_3d",1.6f),E(6.2,"phantom_wail_area_2d",1.4f)),H(Hint(1.2,"zoom",.5),Hint(4.2,"shake",1),Hint(6.2,"slowmo",.3)),G(Gate(1.2,"gate_formed"),Gate(4,"hand_release"))),
            C("blade_tempest_ultimate_3d","ultimate","3d",5f,"#C52319","#FF6A24","#FFD776",T(
                E(0,"focus_charge_3d"),S(.55,"focus_charge_3d"),E(.6,"slash_3d_stylized",.85f,Pos(-.8f,.3f,0),Rot(0,0,-25)),E(.65,"gale_dash_trail_2d",1.3f),S(.88,"gale_dash_trail_2d"),E(.9,"slash_3d_stylized",.9f,Pos(.7f,.2f,0),Rot(0,0,155)),E(1.2,"slash_3d_stylized",1f,Pos(-.4f,-.5f,0),Rot(0,0,15)),E(1.5,"slash_3d_stylized",1.05f,Pos(.5f,-.4f,0),Rot(0,0,195)),E(1.8,"slash_3d_stylized",1.12f,Pos(-.2f,.7f,0),Rot(0,0,-55)),E(2.1,"slash_3d_stylized",1.18f,Pos(.2f,-.7f,0),Rot(0,0,125)),E(2.4,"slash_3d_stylized",1.25f,Pos(-.1f,0,0),Rot(0,0,-5)),E(2.7,"slash_3d_stylized",1.4f,Pos(.1f,0,0),Rot(0,0,175)),E(3.5,"parry_spark_impact_3d",1.25f)),H(Hint(.6,"slowmo",.2),Hint(2.7,"shake",.75),Hint(3.5,"zoom",.4)))
        };

        public static readonly HeroExclusiveEntry[] Exclusives =
        {
            X("katana_sheath_ember_idle_3d","aura","3d","stylized","#B21E18","#FF6725","#FFD278",1.2f,"{'hit':{'type':'single'},'emission':{'type':'single'},'timing':{'type':'sustained'}}"),
            X("flame_dash_slash_3d","slash","3d","stylized","#D72B18","#FF7429","#FFE09A",.55f,"{'hit':{'type':'single'},'emission':{'type':'single'},'timing':{'type':'instant'}}"),
            X("moonwheel_boomerang_projectile_3d","projectile","3d","crystal","#3E9FE7","#A9EEFF","#FFFFFF",1.4f,"{'motion':{'type':'boomerang','out_distance':4,'hover_time':.15,'return_speed':6},'hit':{'type':'single'},'emission':{'type':'single'},'timing':{'type':'instant'}}"),
            X("staff_charge_idle_aura_3d","aura","3d","crystal","#479FE5","#A8EEFF","#FFFFFF",1.2f,"{'hit':{'type':'single'},'emission':{'type':'single'},'timing':{'type':'sustained'}}"),
            X("frost_nova_impact_3d","impact","3d","crystal","#328CD0","#8DE8FF","#FFFFFF",.75f,"{'motion':{'type':'expand_ring','max_radius':4,'expand_speed':5,'edge_thickness':.2},'hit':{'type':'single'},'emission':{'type':'ring','count':10,'ring_radius':1},'timing':{'type':'instant'}}"),
            X("chain_grapple_beam_3d","beam","3d","steampunk","#8C632B","#D9B96E","#C9F5FF",1.2f,"{'hit':{'type':'arc_link','hop_count':1,'sag':.22,'jitter':.025},'emission':{'type':'single'},'timing':{'type':'sustained'}}"),
            X("overheat_vent_idle_aura_3d","aura","3d","steampunk","#7A4924","#D69B54","#F4EFE0",1.2f,"{'hit':{'type':'single'},'emission':{'type':'single'},'timing':{'type':'sustained'}}"),
            X("talisman_barrier_shield_2d","shield","2d","ghost","#385A54","#93D7CB","#F0FFF9",1.2f,"{'hit':{'type':'single'},'emission':{'type':'single'},'timing':{'type':'instant'}}")
        };

        public static readonly CompositePlanEntry HundredGhosts = C("hundred_ghosts_ultimate_2d","hero_component","2d",4.8f,"#222125","#746F78","#B9463A",T(E(0,"ink_dragon_trail_2d",1,Pos(-1,.2f,0)),E(.45,"ink_dragon_trail_2d",1,Pos(0,-.3f,0),Rot(0,0,12)),E(.9,"ink_dragon_trail_2d",1,Pos(1,.25f,0),Rot(0,0,-12)),E(1.4,"phantom_wail_area_2d",1.6f),E(3,"shadow_grasp_area_2d",1.35f)),H(Hint(1.4,"slowmo",.3),Hint(3,"shake",.45)));

        public static readonly CompositePlanEntry[] HeroKits =
        {
            Kit("flame_blade_samurai_kit_showcase_3d","3d",6.8f,"samurai_fire","crescent_sharp","#B31E17","#FF6928","#FFD889",T(E(0,"hero_entrance_lifecycle_3d"),E(.8,"katana_sheath_ember_idle_3d"),S(1.3,"katana_sheath_ember_idle_3d"),E(1.4,"katana_trail_weapon_3d",.8f),S(1.75,"katana_trail_weapon_3d"),E(1.8,"katana_trail_weapon_3d",1),S(2.15,"katana_trail_weapon_3d"),E(2.2,"katana_trail_weapon_3d",1.2f),S(2.55,"katana_trail_weapon_3d"),E(2.8,"flame_dash_slash_3d",1.2f),E(3.8,"blade_tempest_ultimate_3d",.8f),S(5.35,"blade_tempest_ultimate_3d"),E(5.5,"parry_spark_impact_3d"),E(6.1,"death_dissolve_lifecycle_3d"))),
            Kit("ice_moon_mage_kit_showcase_3d","3d",7.2f,"ice_moon","hex_circle","#318ED2","#8EE8FF","#FFFFFF",T(E(0,"twin_portal_3d"),E(.8,"staff_charge_idle_aura_3d"),S(1.25,"staff_charge_idle_aura_3d"),E(1.3,"ice_shard_projectile_2d"),S(1.95,"twin_portal_3d"),E(2,"moonwheel_boomerang_projectile_3d"),E(2.8,"frost_nova_impact_3d"),E(3.7,"crystal_shield_3d_crystal"),E(4.8,"frozen_domain_ultimate_3d",.72f))),
            Kit("mechanical_hunter_kit_showcase_3d","3d",6.6f,"hunter_steam_holo","gear_line","#8C642E","#D9B96E","#7FEAFF",T(E(0,"glitch_blink_transform_3d"),E(.7,"overheat_vent_idle_aura_3d"),E(1.2,"muzzle_flash_impact_3d"),E(1.45,"muzzle_flash_impact_3d"),E(1.7,"muzzle_flash_impact_3d"),E(2.3,"steam_vent_burst_impact_3d"),E(3,"holo_scan_area_3d"),E(4,"chain_grapple_beam_3d"),E(5.2,"emp_nova_impact_2d"))),
            Kit("ghost_curse_shrine_kit_showcase_2d","2d",7f,"ghost_ink","ribbon_talisman","#24252A","#78757E","#B84A42",T(E(0,"talisman_barrier_shield_2d"),E(.8,"arcane_missile_projectile_2d"),E(1.7,"shadow_grasp_area_2d"),E(2.6,"curse_mark_status_2d"),E(3.4,"phantom_wail_area_2d"),E(4.5,"hundred_ghosts_ultimate_2d",.75f)))
        };
        public static IEnumerable<CompositePlanEntry> AllComposites { get { return Ultimates.Concat(new[]{HundredGhosts}).Concat(HeroKits); } }

        private static CompositePlanEntry C(string id,string group,string dim,float duration,string p,string s,string a,JArray timeline,JArray hints=null,JArray gates=null){return new CompositePlanEntry{Id=id,Group=group,Dimension=dim,Duration=duration,Primary=p,Secondary=s,Accent=a,Timeline=timeline,CameraHints=hints??new JArray(),Gates=gates??new JArray()};}
        private static CompositePlanEntry Kit(string id,string dim,float duration,string theme,string shape,string p,string s,string a,JArray timeline){var v=C(id,"hero_kit",dim,duration,p,s,a,timeline);v.ThemeId=theme;v.ShapeLanguage=shape;return v;}
        private static HeroExclusiveEntry X(string id,string archetype,string dim,string style,string p,string s,string a,float duration,string behavior){return new HeroExclusiveEntry{Id=id,Archetype=archetype,Dimension=dim,Style=style,Primary=p,Secondary=s,Accent=a,Duration=duration,Behavior=behavior};}
        private static JArray T(params JObject[] values){return new JArray(values);} private static JArray H(params JObject[] values){return new JArray(values);} private static JArray G(params JObject[] values){return new JArray(values);}
        private static JObject Hint(double t,string type,double strength){return new JObject{{"t",t},{"type",type},{"strength",strength}};} private static JObject Gate(double t,string id){return new JObject{{"t",t},{"wait_for",id}};}
        private static JArray Pos(float x,float y,float z){return new JArray(x,y,z);} private static JArray Rot(float x,float y,float z){return new JArray(x,y,z);}
        private static JObject E(double t,string id,float scale=1,JArray position=null,JArray rotation=null){var o=new JObject{{"t",t},{"ref_id",id},{"action","play"}};var v=new JObject{{"scale",scale}};if(position!=null)v["position"]=position;if(rotation!=null)v["rotation"]=rotation;o["overrides"]=v;return o;}
        private static JObject S(double t,string id){return new JObject{{"t",t},{"ref_id",id},{"action","stop"}};}
    }

    public sealed class CompositeBuildResult { public bool Succeeded,Unchanged; public string PrefabPath,RecipeHash,BuildHash; public ValidationReport Report=new ValidationReport(); }

    public static class CompositeContentCompiler
    {
        public const string CompilerVersion="composite-runtime-1";
        public static ValidationReport ValidateJson(string json)
        {
            var report=new ValidationReport();var parsed=VfxDomainParser.ParseRecipe(json);report.AddRange(parsed.Report);if(report.HasErrors)return report;var recipe=parsed.Value;var plan=CompositeAndHeroKitCatalog.AllComposites.FirstOrDefault(v=>v.Id==recipe.Id);if(plan==null){report.Add("E1856",ValidationSeverity.Error,"/id","Composite id is not registered.",new JValue(recipe.Id));return report;}foreach(var item in recipe.Composite.Timeline.Where(v=>v.Action=="play").GroupBy(v=>v.RefId,StringComparer.Ordinal).Select(v=>v.First())){var path=DependencyPrefabPath(item.RefId);if(AssetDatabase.LoadAssetAtPath<GameObject>(path)==null)report.Add("E1857",ValidationSeverity.Error,"/timeline/"+item.RefId,"Referenced Runtime Entry Prefab is missing.",new JValue(path));}if(report.HasErrors)return report;var peak=PeakBudget(recipe);var limits=(JObject)peak["limits"];foreach(var key in new[]{"particles","particleSystems","materials","renderers"})if((int)peak[key]>(int)limits[key])report.Add("E1859",ValidationSeverity.Error,"/budget/"+key,"Composite peak exceeds the registered composition limit.",peak[key],limits[key].ToString());return report;
        }
        public static CompositeBuildResult BuildAsset(string recipePath)
        {
            var absolute=Absolute(recipePath);if(!File.Exists(absolute)){var missing=new CompositeBuildResult();missing.Report.Add("E1856",ValidationSeverity.Error,"/recipe","Composite Recipe is missing.",new JValue(recipePath));return missing;}return BuildCore(recipePath,File.ReadAllText(absolute));
        }
        public static CompositeBuildResult BuildJsonForTransaction(string recipePath,string recipeJson){return BuildCore(recipePath,recipeJson);}
        private static CompositeBuildResult BuildCore(string recipePath,string json)
        {
            var result=new CompositeBuildResult();var catalog=VfxCompiler.LoadFormalCatalog();result.Report.AddRange(RecipeValidator.Validate(json,catalog));if(result.Report.HasErrors)return result;var recipe=VfxDomainParser.ParseRecipe(json).Value;var plan=CompositeAndHeroKitCatalog.AllComposites.FirstOrDefault(v=>v.Id==recipe.Id);if(plan==null){result.Report.Add("E1856",ValidationSeverity.Error,"/id","Composite id is not registered.",new JValue(recipe.Id));return result;}
            var prefabs=new List<GameObject>();var dependencyParts=new List<string>();foreach(var item in recipe.Composite.Timeline.Where(v=>v.Action=="play")){var path=DependencyPrefabPath(item.RefId);var prefab=AssetDatabase.LoadAssetAtPath<GameObject>(path);if(prefab==null){result.Report.Add("E1857",ValidationSeverity.Error,"/timeline/"+item.RefId,"Referenced Runtime Entry Prefab is missing.",new JValue(path));continue;}prefabs.Add(prefab);dependencyParts.Add(item.RefId+":"+AssetDatabase.GetAssetDependencyHash(path));}if(result.Report.HasErrors)return result;
            var recipeHash=RecipeCanonicalizer.ComputeSha256(json);var buildHash=Hash(recipeHash+"|"+CompilerVersion+"|"+string.Join("|",dependencyParts.ToArray())+"|"+Application.unityVersion);result.RecipeHash=recipeHash;result.BuildHash=buildHash;var folder="Assets/VFX/Generated/"+recipe.Id;var prefabPath=PrefabPath(recipe.Id);var descriptorPath=folder+"/Composition.json";result.PrefabPath=prefabPath;if(ReadBuildHash(recipe.Id)==buildHash&&AssetDatabase.LoadAssetAtPath<GameObject>(prefabPath)!=null&&AssetDatabase.LoadAssetAtPath<TextAsset>(descriptorPath)!=null){result.Succeeded=true;result.Unchanged=true;return result;}
            VfxStyleSharedLibrary.EnsureFolder(folder);Write(descriptorPath,Descriptor(recipe,plan));AssetDatabase.ImportAsset(descriptorPath,ImportAssetOptions.ForceSynchronousImport);var root=new GameObject("VFX_"+recipe.Id);try{var controller=root.AddComponent<CompositeVfxController>();var so=new SerializedObject(controller);so.FindProperty("compositionId").stringValue=recipe.Id;so.FindProperty("duration").floatValue=plan.Duration;so.FindProperty("descriptor").objectReferenceValue=AssetDatabase.LoadAssetAtPath<TextAsset>(descriptorPath);var sources=so.FindProperty("sourcePrefabs");sources.arraySize=prefabs.Count;for(var i=0;i<prefabs.Count;i++)sources.GetArrayElementAtIndex(i).objectReferenceValue=prefabs[i];WriteEvents(so.FindProperty("timeline"),recipe,plan);WriteHints(so.FindProperty("cameraHints"),recipe);WriteGates(so.FindProperty("gates"),recipe);so.ApplyModifiedPropertiesWithoutUndo();if(PrefabUtility.SaveAsPrefabAsset(root,prefabPath)==null)throw new InvalidOperationException("Could not save "+prefabPath);}catch(Exception e){result.Report.Add("E1858",ValidationSeverity.Error,"/build",e.Message);return result;}finally{UnityEngine.Object.DestroyImmediate(root);}AssetDatabase.SaveAssets();var audit=VfxProductionRules.EnforceAndWriteManifest(recipe.Id,"composite",recipe.RecipeVersion,recipe.Revision,recipeHash,buildHash,CompilerVersion,prefabPath,folder,plan.Duration,recipePath);result.Report.AddRange(audit.Report);if(!result.Report.HasErrors)AugmentManifest(recipe,plan);result.Succeeded=!result.Report.HasErrors;return result;
        }
        private static void WriteEvents(SerializedProperty property,Recipe recipe,CompositePlanEntry plan){property.arraySize=recipe.Composite.Timeline.Count;var playIndex=0;var last=new Dictionary<string,int>(StringComparer.Ordinal);for(var i=0;i<recipe.Composite.Timeline.Count;i++){var source=recipe.Composite.Timeline[i];var target=property.GetArrayElementAtIndex(i);var sourceIndex=source.Action=="play"?playIndex++:(last.ContainsKey(source.RefId)?last[source.RefId]:-1);if(source.Action=="play")last[source.RefId]=sourceIndex;target.FindPropertyRelative("Time").floatValue=(float)source.Time;target.FindPropertyRelative("SourceIndex").intValue=sourceIndex;target.FindPropertyRelative("RefId").stringValue=source.RefId;target.FindPropertyRelative("Action").stringValue=source.Action;target.FindPropertyRelative("Scale").floatValue=Number(source.Overrides,"scale",1);target.FindPropertyRelative("Position").vector3Value=Vector(source.Overrides,"position");target.FindPropertyRelative("Rotation").vector3Value=Vector(source.Overrides,"rotation");target.FindPropertyRelative("HasPalette").boolValue=true;target.FindPropertyRelative("Primary").colorValue=ColorOf(plan.Primary);target.FindPropertyRelative("Secondary").colorValue=ColorOf(plan.Secondary);target.FindPropertyRelative("Accent").colorValue=ColorOf(plan.Accent);}}
        private static void WriteHints(SerializedProperty p,Recipe recipe){p.arraySize=recipe.Composite.CameraHints.Count;for(var i=0;i<recipe.Composite.CameraHints.Count;i++){var s=recipe.Composite.CameraHints[i];var t=p.GetArrayElementAtIndex(i);t.FindPropertyRelative("Time").floatValue=(float)s.Time;t.FindPropertyRelative("Type").stringValue=s.Type;t.FindPropertyRelative("Strength").floatValue=(float)s.Strength;}}
        private static void WriteGates(SerializedProperty p,Recipe recipe){p.arraySize=recipe.Composite.Gates.Count;for(var i=0;i<recipe.Composite.Gates.Count;i++){var s=recipe.Composite.Gates[i];var t=p.GetArrayElementAtIndex(i);t.FindPropertyRelative("Time").floatValue=(float)s.Time;t.FindPropertyRelative("WaitFor").stringValue=s.WaitFor;}}
        private static JObject Descriptor(Recipe recipe,CompositePlanEntry plan){return new JObject{{"schema","vfx-composition/1"},{"id",recipe.Id},{"group",plan.Group},{"duration",plan.Duration},{"theme",plan.ThemeId},{"shapeLanguage",plan.ShapeLanguage},{"palette",new JObject{{"primary",plan.Primary},{"secondary",plan.Secondary},{"accent",plan.Accent}}},{"timeline",JArray.FromObject(recipe.Composite.Timeline.Select(v=>new{t=v.Time,ref_id=v.RefId,action=v.Action,overrides=v.Overrides}))},{"camera_hints",JArray.FromObject(recipe.Composite.CameraHints.Select(v=>new{t=v.Time,type=v.Type,strength=v.Strength}))},{"gates",JArray.FromObject(recipe.Composite.Gates.Select(v=>new{t=v.Time,wait_for=v.WaitFor}))},{"peakBudget",PeakBudget(recipe)},{"ownership","dependency-reference-only"}};}
        private static void AugmentManifest(Recipe recipe,CompositePlanEntry plan){var path=VfxProjectRules.ManifestAbsolutePath(recipe.Id);var root=JObject.Parse(File.ReadAllText(path));root["timeline"]=JArray.FromObject(recipe.Composite.Timeline.Select(v=>new{t=v.Time,ref_id=v.RefId,action=v.Action,overrides=v.Overrides}));root["cameraHints"]=JArray.FromObject(recipe.Composite.CameraHints.Select(v=>new{t=v.Time,type=v.Type,strength=v.Strength}));root["gates"]=JArray.FromObject(recipe.Composite.Gates.Select(v=>new{t=v.Time,wait_for=v.WaitFor}));root["themeId"]=plan.ThemeId;root["compositePeakBudget"]=PeakBudget(recipe);WriteAbsolute(path,root.ToString(Formatting.Indented));}
        private sealed class ActiveCost{public string RefId;public double Start,End;public int Particles,Systems,Materials,Renderers;}
        private static JObject PeakBudget(Recipe recipe)
        {
            var active=new List<ActiveCost>();foreach(var item in recipe.Composite.Timeline){if(item.Action=="stop"){var prior=active.LastOrDefault(v=>v.RefId==item.RefId&&v.End>item.Time);if(prior!=null)prior.End=item.Time;continue;}var path=VfxProjectRules.ManifestAbsolutePath(item.RefId);if(!File.Exists(path))continue;var m=JObject.Parse(File.ReadAllText(path));var cost=(JObject)(m["compositePeakBudget"]??m["cost"]);var duration=(double?)m.SelectToken("cost.duration")??.5;active.Add(new ActiveCost{RefId=item.RefId,Start=item.Time,End=item.Time+Math.Max(.05,duration),Particles=(int?)cost["particles"]??0,Systems=(int?)(cost["particleSystems"]??cost["systems"])??0,Materials=(int?)cost["materials"]??0,Renderers=(int?)cost["renderers"]??0});}var times=active.SelectMany(v=>new[]{v.Start,Math.Max(v.Start,v.End-.00001)}).Distinct().OrderBy(v=>v).ToArray();var peakP=0;var peakS=0;var peakM=0;var peakR=0;foreach(var t in times){var live=active.Where(v=>v.Start<=t&&t<v.End).ToArray();peakP=Math.Max(peakP,live.Sum(v=>v.Particles));peakS=Math.Max(peakS,live.Sum(v=>v.Systems));peakM=Math.Max(peakM,live.Sum(v=>v.Materials));peakR=Math.Max(peakR,live.Sum(v=>v.Renderers));}return new JObject{{"particles",peakP},{"particleSystems",peakS},{"materials",peakM},{"renderers",peakR},{"limits",new JObject{{"particles",200},{"particleSystems",10},{"materials",10},{"renderers",14}}}};
        }
        private static float Number(Dictionary<string,JToken> values,string key,float fallback){JToken token;return values.TryGetValue(key,out token)&&(token.Type==JTokenType.Float||token.Type==JTokenType.Integer)?(float)token:fallback;} private static Vector3 Vector(Dictionary<string,JToken> values,string key){JToken token;var a=values.TryGetValue(key,out token)?token as JArray:null;return a!=null&&a.Count==3?new Vector3((float)a[0],(float)a[1],(float)a[2]):Vector3.zero;} private static Color ColorOf(string value){Color c;return ColorUtility.TryParseHtmlString(value,out c)?c:Color.white;}
        private static string PrefabPath(string id){return "Assets/VFX/Generated/"+id+"/VFX_"+id+".prefab";} private static string DependencyPrefabPath(string id){var p=VfxProjectRules.ManifestAbsolutePath(id);if(File.Exists(p))try{var value=(string)JObject.Parse(File.ReadAllText(p)).SelectToken("runtimeEntry.path");if(!string.IsNullOrEmpty(value))return value;}catch{}return PrefabPath(id);} private static string ReadBuildHash(string id){var p=VfxProjectRules.ManifestAbsolutePath(id);if(!File.Exists(p))return null;try{return(string)JObject.Parse(File.ReadAllText(p))["buildHash"];}catch{return null;}} private static string Hash(string value){using(var sha=SHA256.Create())return string.Concat(sha.ComputeHash(Encoding.UTF8.GetBytes(value)).Select(v=>v.ToString("x2",CultureInfo.InvariantCulture)));} private static string Absolute(string asset){return Path.GetFullPath(Path.Combine(Directory.GetParent(Application.dataPath).FullName,asset.Replace('/',Path.DirectorySeparatorChar)));} private static void Write(string path,JToken value){WriteAbsolute(Absolute(path),value.ToString(Formatting.Indented));} private static void WriteAbsolute(string path,string value){Directory.CreateDirectory(Path.GetDirectoryName(path));var text=value.Replace("\r\n","\n");if(File.Exists(path)&&File.ReadAllText(path)==text)return;File.WriteAllText(path,text,new UTF8Encoding(false));}
    }

    public static class CompositeAndHeroKitAuthoring
    {
        public const string RecipeRoot="Assets/VFX/Recipes/Composites";public const string PatchRoot="Assets/VFX/Recipes/Patches";public const string PreviewRoot="Assets/VFX/Preview";
        [MenuItem("Tools/VFX Composer/Content/Build W13 W18")]
        public static void BuildAll(){WriteSources();AssetDatabase.Refresh(ImportAssetOptions.ForceSynchronousImport);foreach(var entry in CompositeAndHeroKitCatalog.Exclusives){var result=StyledContentCompiler.BuildAsset(ExclusiveRecipePath(entry));if(!result.Succeeded)throw new InvalidOperationException(entry.Id+": "+string.Join(" | ",result.Report.Entries.Select(v=>v.Code+" "+v.Path+" "+v.Message)));}foreach(var entry in CompositeAndHeroKitCatalog.AllComposites){var result=CompositeContentCompiler.BuildAsset(CompositeRecipePath(entry));if(!result.Succeeded)throw new InvalidOperationException(entry.Id+": "+string.Join(" | ",result.Report.Entries.Select(v=>v.Code+" "+v.Path+" "+v.Message)));}BuildPreview("ultimate");BuildPreview("hero_kit");AssetDatabase.SaveAssets();AssetDatabase.Refresh();}
        public static void WriteSources(){VfxStyleSharedLibrary.EnsureFolder(RecipeRoot);VfxStyleSharedLibrary.EnsureFolder(RecipeRoot+"/Ultimate");VfxStyleSharedLibrary.EnsureFolder(RecipeRoot+"/HeroKits");VfxStyleSharedLibrary.EnsureFolder(RecipeRoot+"/HeroComponents");VfxStyleSharedLibrary.EnsureFolder(PatchRoot);foreach(var e in CompositeAndHeroKitCatalog.Exclusives){Write(ExclusiveRecipePath(e),ExclusiveRecipe(e));WritePatch(e.Id);}foreach(var e in CompositeAndHeroKitCatalog.AllComposites){Write(CompositeRecipePath(e),CompositeRecipe(e));WritePatch(e.Id);}}
        public static string CompositeRecipePath(CompositePlanEntry e){return RecipeRoot+"/"+(e.Group=="ultimate"?"Ultimate":e.Group=="hero_kit"?"HeroKits":"HeroComponents")+"/"+e.Id+".default.json";} public static string ExclusiveRecipePath(HeroExclusiveEntry e){return RecipeRoot+"/HeroComponents/"+e.Id+".default.json";}
        public static string PreviewPath(string group){return PreviewRoot+(group=="ultimate"?"/VFXPREVIEW_Ultimate.unity":"/VFXPREVIEW_HeroKits.unity");}
        private static JObject CompositeRecipe(CompositePlanEntry e){var recipe=Base(e.Id,e.Dimension,"composite","stylized",e.Primary,e.Secondary,e.Accent,e.Duration);recipe["timeline"]=e.Timeline.DeepClone();foreach(var item in (JArray)recipe["timeline"]){var overrides=(JObject)item["overrides"];if(overrides!=null)overrides["palette"]=e.ThemeId??e.Group;}recipe["camera_hints"]=e.CameraHints.DeepClone();recipe["gates"]=e.Gates.DeepClone();recipe["metadata"]["createdBy"]="w13-w18-composite";return recipe;}
        private static JObject ExclusiveRecipe(HeroExclusiveEntry e){var recipe=Base(e.Id,e.Dimension,e.Archetype,e.Style,e.Primary,e.Secondary,e.Accent,e.Duration);recipe["behavior"]=JObject.Parse(e.Behavior.Replace(":.",":0."));recipe["metadata"]["createdBy"]="w18-hero-exclusive";return recipe;}
        private static JObject Base(string id,string dim,string archetype,string style,string p,string s,string a,float duration){var d=dim=="2d"?"2D":"3D";return new JObject{{"recipeVersion",1},{"revision",1},{"id",id},{"name",Title(id)},{"dimension",dim},{"archetype",archetype},{"style",new JObject{{"token",style},{"palette",new JObject{{"primary",p},{"secondary",s},{"accent",a}}},{"outline",.1},{"shading_steps",4},{"noise_scale",1.2},{"glow_strength",1.05}}},{"targetProfile","mobile_medium"},{"randomSeed",Seed(id)},{"stages",new JArray{new JObject{{"id","main"},{"trigger","manual"},{"duration",duration},{"enabled",true},{"modules",new JArray{new JObject{{"id","body"},{"kind","energy_body"},{"templateId","PFT_"+d+"_FireCore"},{"parameters",new JObject{{"scale",1.0}}},{"enabled",true}}}}}}},{"metadata",new JObject{{"createdBy","w13-w18"},{"templateCatalogVersion","1.0.0"}}}};}
        private static void WritePatch(string id){Write(PatchRoot+"/"+id+".semantic.patch.json",new JArray{new JObject{{"op","set_palette"},{"path","/style/palette/accent"},{"value","#E8FFFF"}}});}
        private static void BuildPreview(string group){VfxStyleSharedLibrary.EnsureFolder(PreviewRoot);var scene=EditorSceneManager.NewScene(NewSceneSetup.EmptyScene,NewSceneMode.Single);var cameraGo=new GameObject(group=="ultimate"?"UltimateReviewCamera":"HeroKitReviewCamera");var camera=cameraGo.AddComponent<Camera>();camera.tag="MainCamera";camera.clearFlags=CameraClearFlags.SolidColor;camera.backgroundColor=new Color(.012f,.015f,.022f);camera.orthographic=true;camera.orthographicSize=4.2f;camera.transform.position=new Vector3(0,0,-12);camera.allowHDR=false;camera.allowMSAA=false;var plans=(group=="ultimate"?CompositeAndHeroKitCatalog.Ultimates:CompositeAndHeroKitCatalog.HeroKits).ToArray();var controllers=new List<CompositeVfxController>();for(var i=0;i<plans.Length;i++){var p=plans[i];var prefab=AssetDatabase.LoadAssetAtPath<GameObject>("Assets/VFX/Generated/"+p.Id+"/VFX_"+p.Id+".prefab");var instance=(GameObject)PrefabUtility.InstantiatePrefab(prefab,scene);instance.name="ReviewSlot_"+(i+1).ToString("00")+"_"+p.Id;instance.SetActive(i==0);controllers.Add(instance.GetComponent<CompositeVfxController>());}var driverGo=new GameObject("CompositePreviewDriver");var driver=driverGo.AddComponent<CompositePreviewDriver>();var so=new SerializedObject(driver);var entries=so.FindProperty("entries");entries.arraySize=controllers.Count;for(var i=0;i<controllers.Count;i++)entries.GetArrayElementAtIndex(i).objectReferenceValue=controllers[i];so.FindProperty("reviewCamera").objectReferenceValue=camera;so.ApplyModifiedPropertiesWithoutUndo();EditorSceneManager.SaveScene(scene,PreviewPath(group));}
        private static string Title(string id){return string.Join(" ",id.Split('_').Select(v=>v.Length==0?v:char.ToUpperInvariant(v[0])+v.Substring(1)));} private static uint Seed(string id){unchecked{uint h=2166136261;foreach(var c in id){h^=c;h*=16777619;}return h;}} private static string Absolute(string asset){return Path.GetFullPath(Path.Combine(Directory.GetParent(Application.dataPath).FullName,asset.Replace('/',Path.DirectorySeparatorChar)));} private static void Write(string path,JToken value){var absolute=Absolute(path);Directory.CreateDirectory(Path.GetDirectoryName(absolute));var text=value.ToString(Formatting.Indented).Replace("\r\n","\n");if(File.Exists(absolute)&&File.ReadAllText(absolute)==text)return;File.WriteAllText(absolute,text,new UTF8Encoding(false));}
    }
}
